// 各讲义的专业术语和四级词汇
const lectureData = {
    // 第一讲内容 - 模板：{ term: "词汇", pos: "词性", phonetic: "音标", definition: "定义" }
    1: [
        { term: "Machine Learning (ML)", pos: "n.", phonetic: "/məˈʃiːn ˈlɜːnɪŋ/", definition: "机器学习 - 让计算机从数据中学习而不需要明确编程的科学" },
        { term: "Inductive learning", pos: "n.", phonetic: "/ɪnˈdʌktɪv ˈlɜːnɪŋ/", definition: "归纳学习 - 从特定样例集中获得通用结论的逻辑推理形式" },
        { term: "Supervised learning", pos: "n.", phonetic: "/ˈsuːpəvaɪzd ˈlɜːnɪŋ/", definition: "监督学习 - 使用已标记的训练数据来学习输入到输出的映射" },
        { term: "Unsupervised learning", pos: "n.", phonetic: "/ˌʌnˈsuːpəvaɪzd ˈlɜːnɪŋ/", definition: "无监督学习 - 使用未标记的数据发现其中的模式或结构" },
        { term: "Classification", pos: "n.", phonetic: "/ˌklæsɪfɪˈkeɪʃn/", definition: "分类 - 将输入数据划分到已定义的类别中的任务" },
        { term: "Regression", pos: "n.", phonetic: "/rɪˈɡreʃn/", definition: "回归 - 预测连续数值输出的任务" },
        { term: "Training set", pos: "n.", phonetic: "/ˈtreɪnɪŋ set/", definition: "训练集 - 用于训练机器学习模型的数据集" },
        { term: "Test set", pos: "n.", phonetic: "/test set/", definition: "测试集 - 用于评估模型性能的独立数据集" },
        { term: "Validation set", pos: "n.", phonetic: "/ˌvælɪˈdeɪʃn set/", definition: "验证集 - 用于调整超参数的额外数据集" },
        { term: "Attribute/Feature", pos: "n.", phonetic: "/ˈætrɪbjuːt/ˈfiːtʃə/", definition: "属性/特征 - 描述实例特征的变量" },
        { term: "Instance/Example", pos: "n.", phonetic: "/ˈɪnstəns/ɪɡˈzɑːmpl/", definition: "实例/样本 - 描述对象的属性值元组" },
        { term: "Label/Target feature", pos: "n.", phonetic: "/ˈleɪbl/ˈtɑːɡɪt ˈfiːtʃə/", definition: "标签/目标特征 - 描述要预测的现象的特殊属性" },
        { term: "Data set", pos: "n.", phonetic: "/ˈdeɪtə set/", definition: "数据集 - 由实例及其相应属性值和标签组成的集合" },
        { term: "Descriptive features", pos: "n.", phonetic: "/dɪˈskrɪptɪv ˈfiːtʃəz/", definition: "描述性特征 - 用于描述实例的属性" },
        { term: "Target function", pos: "n.", phonetic: "/ˈtɑːɡɪt ˈfʌŋkʃn/", definition: "目标函数 - 从输入空间到输出空间的理想映射" },
        { term: "Hypothesis space", pos: "n.", phonetic: "/haɪˈpɒθəsɪs speɪs/", definition: "假设空间 - 学习算法可以考虑的候选函数集合" },
        { term: "Learning model", pos: "n.", phonetic: "/ˈlɜːnɪŋ ˈmɒdl/", definition: "学习模型 - 由学习算法和假设集组成的系统" },
        { term: "Classifier", pos: "n.", phonetic: "/ˈklæsɪfaɪə/", definition: "分类器 - 将输入分配到预定义类别的模型" },
        { term: "Instance-based learning", pos: "n.", phonetic: "/ˈɪnstəns beɪst ˈlɜːnɪŋ/", definition: "基于实例的学习 - 通过比较新实例与学习到的实例来泛化" },
        { term: "Model-based learning", pos: "n.", phonetic: "/ˈmɒdl beɪst ˈlɜːnɪŋ/", definition: "基于模型的学习 - 从训练样本构建模型并用于预测" },
        { term: "Clustering", pos: "n.", phonetic: "/ˈklʌstərɪŋ/", definition: "聚类 - 将数据分组到相似实例集合的无监督方法" },
        { term: "K-means clustering", pos: "n.", phonetic: "/keɪ miːnz ˈklʌstərɪŋ/", definition: "K均值聚类 - 将数据分为K个聚类的算法" },
        { term: "DBSCAN", pos: "n.", phonetic: "/diː biː skæn/", definition: "基于密度的空间聚类 - 根据密度定义区域发现聚类的算法" },
        { term: "Hierarchical Cluster Analysis (HCA)", pos: "n.", phonetic: "/haɪəˈrɑːkɪkl ˈklʌstə əˈnæləsɪs/", definition: "层次聚类分析 - 创建聚类层次结构的方法" },
        { term: "Principal Component Analysis (PCA)", pos: "n.", phonetic: "/ˈprɪnsəpl kəmˈpəʊnənt əˈnæləsɪs/", definition: "主成分分析 - 降低数据维度同时保留变异的技术" },
        { term: "Dimensionality reduction", pos: "n.", phonetic: "/daɪˌmenʃəˈnælɪti rɪˈdʌkʃn/", definition: "降维 - 减少数据特征数量的过程" },
        { term: "Anomaly detection", pos: "n.", phonetic: "/əˈnɒməli dɪˈtekʃn/", definition: "异常检测 - 识别异常实例或离群点的技术" },
        { term: "Generalisation error", pos: "n.", phonetic: "/ˌdʒenərəlaɪˈzeɪʃn ˈerə/", definition: "泛化误差 - 模型在新数据上的错误率" },
        { term: "Out-of-sample error", pos: "n.", phonetic: "/aʊt əv ˈsɑːmpl ˈerə/", definition: "样本外误差 - 模型在训练集之外数据上的表现" },
        { term: "Hyperparameter", pos: "n.", phonetic: "/ˌhaɪpəˈpærəmɪtə/", definition: "超参数 - 学习算法的配置值，不通过训练过程学习" },
        { term: "Overfitting", pos: "n.", phonetic: "/ˌəʊvəˈfɪtɪŋ/", definition: "过拟合 - 模型过度适应训练数据细节而无法泛化的现象" },
        { term: "Underfitting", pos: "n.", phonetic: "/ˌʌndəˈfɪtɪŋ/", definition: "欠拟合 - 模型过于简单，无法捕获数据模式的现象" },
        { term: "Online learning", pos: "n.", phonetic: "/ˈɒnlaɪn ˈlɜːnɪŋ/", definition: "在线学习 - 能够增量学习的系统" },
        { term: "Batch learning", pos: "n.", phonetic: "/bætʃ ˈlɜːnɪŋ/", definition: "批量学习 - 一次性使用所有可用数据训练的系统" },
        { term: "Association rule learning", pos: "n.", phonetic: "/əˌsəʊsɪˈeɪʃn ruːl ˈlɜːnɪŋ/", definition: "关联规则学习 - 发现变量之间关系的方法" },
        { term: "Decision boundary", pos: "n.", phonetic: "/dɪˈsɪʒn ˈbaʊndəri/", definition: "决策边界 - 分类算法中划分不同类别的边界" },
        { term: "Locally-Linear Embedding (LLE)", pos: "n.", phonetic: "/ˈləʊkəli ˈlɪnɪə ɪmˈbedɪŋ/", definition: "局部线性嵌入 - 用于降维的非线性技术" },
        { term: "t-distributed Stochastic Neighbor Embedding (t-SNE)", pos: "n.", phonetic: "/tiː dɪsˈtrɪbjuːtɪd stəˈkæstɪk ˈneɪbə ɪmˈbedɪŋ/", definition: "t分布随机邻域嵌入 - 数据可视化降维技术" },
        { term: "Apriori algorithm", pos: "n.", phonetic: "/eɪpriˈɔːri ˈælɡərɪðəm/", definition: "Apriori算法 - 用于关联规则学习的经典算法" },
        { term: "Eclat algorithm", pos: "n.", phonetic: "/ɪˈklæt ˈælɡərɪðəm/", definition: "Eclat算法 - 高效的关联规则挖掘算法" },
        { term: "Reinforcement learning", pos: "n.", phonetic: "/ˌriːɪnˈfɔːsmənt ˈlɜːnɪŋ/", definition: "强化学习 - 通过与环境交互学习最优策略的机器学习方法" },
        { term: "Semi-supervised learning", pos: "n.", phonetic: "/ˌsemiˈsuːpəvaɪzd ˈlɜːnɪŋ/", definition: "半监督学习 - 结合少量标记数据和大量未标记数据的学习方法" },
        { term: "Acquisition", pos: "n.", phonetic: "/ˌækwɪˈzɪʃn/", definition: "获取 - 获得或收集数据或知识的过程" },
        { term: "Inference", pos: "n.", phonetic: "/ˈɪnfərəns/", definition: "推理 - 从已知信息或证据得出结论的过程" },
        { term: "Generic", pos: "adj.", phonetic: "/dʒəˈnerɪk/", definition: "通用的 - 适用于整个类别而非特定个体的" },
        { term: "Conclusion", pos: "n.", phonetic: "/kənˈkluːʒn/", definition: "结论 - 通过推理得出的判断或决定" },
        { term: "Particular", pos: "adj.", phonetic: "/pəˈtɪkjələ/", definition: "特定的 - 与其他事物区别的特殊的或明确的" },
        { term: "Phenomenon", pos: "n.", phonetic: "/fəˈnɒmɪnən/", definition: "现象 - 可观察到的事件或事实" },
        { term: "Tuple", pos: "n.", phonetic: "/ˈtjuːpl/", definition: "元组 - 有序的元素集合" },
        { term: "Vector", pos: "n.", phonetic: "/ˈvektə/", definition: "向量 - 具有大小和方向的量" },
        { term: "Associate", pos: "v.", phonetic: "/əˈsəʊʃɪeɪt/", definition: "关联 - 将事物或概念连接起来" },
        { term: "Construct", pos: "v.", phonetic: "/kənˈstrʌkt/", definition: "构建 - 创建或形成某物" },
        { term: "Automate", pos: "v.", phonetic: "/ˈɔːtəmeɪt/", definition: "自动化 - 使过程或系统自动运行" },
        { term: "Evaluate", pos: "v.", phonetic: "/ɪˈvæljueɪt/", definition: "评估 - 确定某物的价值或重要性" },
        { term: "Incrementally", pos: "adv.", phonetic: "/ˌɪnkrəˈmentəli/", definition: "递增地 - 以渐进的方式" },
        { term: "Generalise", pos: "v.", phonetic: "/ˈdʒenərəlaɪz/", definition: "泛化 - 从特定情况中推导出普遍原则" },
        { term: "Threshold", pos: "n.", phonetic: "/ˈθreʃəʊld/", definition: "阈值 - 触发效应或行动的临界点" },
        { term: "Coordinate", pos: "n.", phonetic: "/kəʊˈɔːdɪnət/", definition: "坐标 - 确定点位置的一组数值" },
        { term: "Candidate", pos: "n.", phonetic: "/ˈkændɪdət/", definition: "候选 - 被考虑接受位置或奖励的人或物" },
        { term: "Insufficient", pos: "adj.", phonetic: "/ˌɪnsəˈfɪʃnt/", definition: "不足的 - 数量或质量不够满足需求的" },
        { term: "Representative", pos: "adj.", phonetic: "/ˌreprɪˈzentətɪv/", definition: "代表性的 - 典型的或能代表整体的" },
        { term: "Relevant", pos: "adj.", phonetic: "/ˈreləvənt/", definition: "相关的 - 与当前主题或情况有关的" },
        { term: "Irrelevant", pos: "adj.", phonetic: "/ɪˈreləvənt/", definition: "不相关的 - 与当前主题或情况无关的" },
        { term: "Explicit", pos: "adj.", phonetic: "/ɪkˈsplɪsɪt/", definition: "明确的 - 清晰表达且不留歧义的" },
        { term: "Parameter", pos: "n.", phonetic: "/pəˈræmɪtə/", definition: "参数 - 定义系统特征或行为的数值" },
        { term: "Bias", pos: "n.", phonetic: "/ˈbaɪəs/", definition: "偏差 - 对某一观点或结果的系统性倾向" },
        { term: "Criteria", pos: "n.", phonetic: "/kraɪˈtɪəriə/", definition: "标准 - 用来判断或决策的原则或标准" },
        { term: "Exclusive", pos: "adj.", phonetic: "/ɪkˈskluːsɪv/", definition: "排他的 - 不包含其他事物或限制参与的" },
        { term: "Objective", pos: "n.", phonetic: "/əbˈdʒektɪv/", definition: "目标 - 希望实现的结果或目的" },
        { term: "Abnormal", pos: "adj.", phonetic: "/æbˈnɔːml/", definition: "异常的 - 偏离正常或预期的" },
        { term: "Hierarchy", pos: "n.", phonetic: "/ˈhaɪərɑːki/", definition: "层次结构 - 按级别或重要性排序的系统" },
        { term: "Stochastic", pos: "adj.", phonetic: "/stəˈkæstɪk/", definition: "随机的 - 包含随机变量或概率的" },
        { term: "Density", pos: "n.", phonetic: "/ˈdensəti/", definition: "密度 - 单位体积或空间内的质量或数量" },
        { term: "Polluted", pos: "adj.", phonetic: "/pəˈluːtɪd/", definition: "受污染的 - 被有害物质污染的" },
        { term: "Visualization", pos: "n.", phonetic: "/ˌvɪʒuəlaɪˈzeɪʃn/", definition: "可视化 - 将数据或概念以图形方式呈现" },
        { term: "Embedded", pos: "adj.", phonetic: "/ɪmˈbedɪd/", definition: "嵌入的 - 固定或包含在更大结构中的" },
        { term: "Embedding", pos: "n.", phonetic: "/ɪmˈbedɪŋ/", definition: "嵌入 - 将对象插入或包含在介质中的过程" }
    ],
    
    // 第二讲内容
    2: [
        { term: "Machine Learning", pos: "n.", phonetic: "/məˈʃiːn ˈlɜːnɪŋ/", definition: "机器学习 - 计算机系统通过数据学习和改进的科学" },
        { term: "Supervised Learning", pos: "n.", phonetic: "/ˈsuːpəvaɪzd ˈlɜːnɪŋ/", definition: "监督学习 - 使用已标记的训练数据进行学习的机器学习方法" },
        { term: "Classification", pos: "n.", phonetic: "/ˌklæsɪfɪˈkeɪʃn/", definition: "分类 - 将数据分到预定义类别的任务" },
        { term: "Regression", pos: "n.", phonetic: "/rɪˈɡreʃn/", definition: "回归 - 预测连续值的任务" },
        { term: "Binary Classification", pos: "n.", phonetic: "/ˈbaɪnəri ˌklæsɪfɪˈkeɪʃn/", definition: "二元分类 - 将数据分为两个类别的任务" },
        { term: "Multiclass Classification", pos: "n.", phonetic: "/ˌmʌltiˈklɑːs ˌklæsɪfɪˈkeɪʃn/", definition: "多类分类 - 将数据分为三个或更多类别的任务" },
        { term: "Feature", pos: "n.", phonetic: "/ˈfiːtʃə/", definition: "特征 - 用于分析的输入变量" },
        { term: "Label/Target Variable", pos: "n.", phonetic: "/ˈleɪbl/ˈtɑːɡɪt ˈveəriəbl/", definition: "标签/目标变量 - 预测的目标输出" },
        { term: "Model Selection", pos: "n.", phonetic: "/ˈmɒdl sɪˈlekʃn/", definition: "模型选择 - 选择最合适的机器学习模型的过程" },
        { term: "Training Set", pos: "n.", phonetic: "/ˈtreɪnɪŋ set/", definition: "训练集 - 用于训练模型的数据集" },
        { term: "Test Set", pos: "n.", phonetic: "/test set/", definition: "测试集 - 用于评估模型性能的数据集" },
        { term: "Hypothesis Space", pos: "n.", phonetic: "/haɪˈpɒθəsɪs speɪs/", definition: "假设空间 - 可能的模型函数的集合" },
        { term: "Vectorisation", pos: "n.", phonetic: "/ˌvektəraɪˈzeɪʃn/", definition: "向量化 - 将操作转换为向量操作以提高效率" },
        { term: "Data Snooping Bias", pos: "n.", phonetic: "/ˈdeɪtə ˈsnuːpɪŋ ˈbaɪəs/", definition: "数据窥探偏差 - 通过查看测试数据导致的偏差" },
        { term: "Confusion Matrix", pos: "n.", phonetic: "/kənˈfjuːʒn ˈmætrɪks/", definition: "混淆矩阵 - 评估分类模型性能的表格" },
        { term: "Precision", pos: "n.", phonetic: "/prɪˈsɪʒn/", definition: "精确率 - 真阳性除以所有预测为阳性的比例" },
        { term: "Recall/Sensitivity", pos: "n.", phonetic: "/rɪˈkɔːl/ˌsensɪˈtɪvɪti/", definition: "召回率/敏感度 - 真阳性除以所有实际阳性的比例" },
        { term: "F1 Score", pos: "n.", phonetic: "/ef wʌn skɔː/", definition: "F1分数 - 精确率和召回率的调和平均值" },
        { term: "True Positive (TP)", pos: "n.", phonetic: "/truː ˈpɒzətɪv/", definition: "真阳性 - 正确预测为阳性的样本" },
        { term: "False Positive (FP)", pos: "n.", phonetic: "/fɔːls ˈpɒzətɪv/", definition: "假阳性 - 错误预测为阳性的样本" },
        { term: "True Negative (TN)", pos: "n.", phonetic: "/truː ˈneɡətɪv/", definition: "真阴性 - 正确预测为阴性的样本" },
        { term: "False Negative (FN)", pos: "n.", phonetic: "/fɔːls ˈneɡətɪv/", definition: "假阴性 - 错误预测为阴性的样本" },
        { term: "ROC Curve", pos: "n.", phonetic: "/ɑr əʊ siː kɜːv/", definition: "ROC曲线 - 受试者工作特征曲线，描述分类器性能的图" },
        { term: "AUC", pos: "n.", phonetic: "/eɪ juː siː/", definition: "曲线下面积 - ROC曲线下的面积，评估分类器整体性能" },
        { term: "Specificity", pos: "n.", phonetic: "/ˌspesɪˈfɪsɪti/", definition: "特异性 - 真阴性除以所有实际阴性的比例" },
        { term: "Logistic Regression", pos: "n.", phonetic: "/ləˈdʒɪstɪk rɪˈɡreʃn/", definition: "逻辑回归 - 用于分类的统计模型" },
        { term: "MNIST Dataset", pos: "n.", phonetic: "/em-nɪst ˈdeɪtəset/", definition: "MNIST数据集 - 手写数字图像的标准数据集" },
        { term: "Sampling Bias", pos: "n.", phonetic: "/ˈsɑːmplɪŋ ˈbaɪəs/", definition: "采样偏差 - 因样本选择不代表总体而产生的误差" },
        { term: "Softmax Regression", pos: "n.", phonetic: "/ˈsɒftmæks rɪˈɡreʃn/", definition: "Softmax回归 - 多类分类的逻辑回归扩展" },
        { term: "Random Forest", pos: "n.", phonetic: "/ˈrændəm ˈfɒrɪst/", definition: "随机森林 - 基于多个决策树的集成学习方法" },
        { term: "Support Vector Machine", pos: "n.", phonetic: "/səˈpɔːt ˈvektə məˈʃiːn/", definition: "支持向量机 - 一种监督学习分类算法" },
        { term: "Naive Bayes", pos: "n.", phonetic: "/naɪˈiːv beɪz/", definition: "朴素贝叶斯 - 基于贝叶斯定理的分类方法" },
        { term: "Automate", pos: "v.", phonetic: "/ˈɔːtəmeɪt/", definition: "自动化 - 使过程不需要人工干预自动进行" },
        { term: "Discriminating", pos: "adj.", phonetic: "/dɪˈskrɪmɪneɪtɪŋ/", definition: "区分的 - 能够识别差异的" },
        { term: "Constraint", pos: "n.", phonetic: "/kənˈstreɪnt/", definition: "约束 - 限制条件" },
        { term: "Incorporate", pos: "v.", phonetic: "/ɪnˈkɔːpəreɪt/", definition: "包含，结合 - 将某物纳入更大的整体中" },
        { term: "Bias", pos: "n.", phonetic: "/ˈbaɪəs/", definition: "偏差 - 系统性的错误" },
        { term: "Threshold", pos: "n.", phonetic: "/ˈθreʃhəʊld/", definition: "阈值 - 触发某种行为或变化的水平或点" },
        { term: "Proportion", pos: "n.", phonetic: "/prəˈpɔːʃn/", definition: "比例 - 部分与整体的关系" },
        { term: "Iteration", pos: "n.", phonetic: "/ˌɪtəˈreɪʃn/", definition: "迭代 - 重复执行某个过程" },
        { term: "Snooping", pos: "n.", phonetic: "/ˈsnuːpɪŋ/", definition: "窥探 - 未经授权地查看" },
        { term: "Validate", pos: "v.", phonetic: "/ˈvælɪdeɪt/", definition: "验证 - 确认正确性或有效性" },
        { term: "Assumption", pos: "n.", phonetic: "/əˈsʌmpʃn/", definition: "假设 - 未经证实但被认为是真的事情" },
        { term: "Reproducibility", pos: "n.", phonetic: "/ˌriːprəˌdjuːsəˈbɪləti/", definition: "可重复性 - 在相同条件下获得相同结果的能力" },
        { term: "Instance", pos: "n.", phonetic: "/ˈɪnstəns/", definition: "实例 - 特定的例子" },
        { term: "Harmony", pos: "n.", phonetic: "/ˈhɑːməni/", definition: "和谐 - 各部分间的协调一致" },
        { term: "Arbitrary", pos: "adj.", phonetic: "/ˈɑːbɪtrəri/", definition: "任意的 - 基于个人判断而非规则的" },
        { term: "Scenario", pos: "n.", phonetic: "/sɪˈnɑːriəʊ/", definition: "场景 - 可能发生的情况" },
        { term: "Predict", pos: "v.", phonetic: "/prɪˈdɪkt/", definition: "预测 - 提前说出将要发生的事" },
        { term: "Specific", pos: "adj.", phonetic: "/spəˈsɪfɪk/", definition: "特定的 - 明确且精确的" },
        { term: "Strictly", pos: "adv.", phonetic: "/ˈstrɪktli/", definition: "严格地 - 完全按照规则或定义" },
        { term: "Specificity", pos: "n.", phonetic: "/ˌspesɪˈfɪsɪti/", definition: "特异性 - 特定或独特的性质" },
        { term: "Revisit", pos: "v.", phonetic: "/ˌriːˈvɪzɪt/", definition: "重访 - 重新考虑或重新探讨" }
    ],
    
    // 第三讲内容
    3: [
        { term: "Linear Regression", pos: "n.", phonetic: "/ˈlɪnɪər rɪˈɡreʃn/", definition: "线性回归 - 一种通过计算输入特征的加权和来进行预测的线性模型" },
        { term: "Gradient Descent", pos: "n.", phonetic: "/ˈɡreɪdiənt dɪˈsent/", definition: "梯度下降 - 一种通过迭代调整参数以最小化成本函数的优化算法" },
        { term: "Polynomial Regression", pos: "n.", phonetic: "/ˌpɒlɪˈnəʊmiəl rɪˈɡreʃn/", definition: "多项式回归 - 使用多项式函数进行拟合的回归分析方法" },
        { term: "Learning Curves", pos: "n.", phonetic: "/ˈlɜːnɪŋ kɜːvz/", definition: "学习曲线 - 显示模型在训练集和验证集上性能随训练集大小变化的图表" },
        { term: "Regularised Linear Models", pos: "n.", phonetic: "/ˈreɡjʊləraɪzd ˈlɪnɪə ˈmɒdlz/", definition: "正则化线性模型 - 添加惩罚项以避免过拟合的线性模型" },
        { term: "Logistic Regression", pos: "n.", phonetic: "/ləˈdʒɪstɪk rɪˈɡreʃn/", definition: "逻辑回归 - 用于估计实例属于特定类别概率的分类算法" },
        { term: "bias term", pos: "n.", phonetic: "/ˈbaɪəs tɜːm/", definition: "偏置项 - 线性模型中的常数项，也称为截距项" },
        { term: "feature weights", pos: "n.", phonetic: "/ˈfiːtʃə weɪts/", definition: "特征权重 - 线性模型中各特征的系数" },
        { term: "Mean Squared Error", pos: "n.", phonetic: "/miːn skweəd ˈerə/", definition: "均方误差 - 回归模型常用的性能评估指标" },
        { term: "Residual Sum of Squares", pos: "n.", phonetic: "/rɪˈzɪdjuəl sʌm əv skweəz/", definition: "残差平方和 - 实际值与预测值差的平方和" },
        { term: "Normal Equation", pos: "n.", phonetic: "/ˈnɔːməl ɪˈkweɪʒn/", definition: "正规方程 - 一种直接计算线性回归最优参数的数学方程" },
        { term: "cost function", pos: "n.", phonetic: "/kɒst ˈfʌŋkʃn/", definition: "成本函数 - 衡量模型性能的函数，训练目标是最小化该函数" },
        { term: "partial derivative", pos: "n.", phonetic: "/ˈpɑːʃl dɪˈrɪvətɪv/", definition: "偏导数 - 多变量函数对某一变量的导数" },
        { term: "gradient vector", pos: "n.", phonetic: "/ˈɡreɪdiənt ˈvektə/", definition: "梯度向量 - 包含函数所有偏导数的向量" },
        { term: "random initialization", pos: "n.", phonetic: "/ˈrændəm ɪˌnɪʃəlaɪˈzeɪʃn/", definition: "随机初始化 - 用随机值初始化模型参数的过程" },
        { term: "learning rate", pos: "n.", phonetic: "/ˈlɜːnɪŋ reɪt/", definition: "学习率 - 控制梯度下降步长的超参数" },
        { term: "Batch GD", pos: "n.", phonetic: "/bætʃ dʒiː diː/", definition: "批量梯度下降 - 使用整个训练集计算梯度的梯度下降变体" },
        { term: "Stochastic GD", pos: "n.", phonetic: "/stəˈkæstɪk dʒiː diː/", definition: "随机梯度下降 - 每步基于单个随机实例计算梯度的梯度下降变体" },
        { term: "Mini-batch GD", pos: "n.", phonetic: "/ˈmɪni bætʃ dʒiː diː/", definition: "小批量梯度下降 - 基于小随机样本集计算梯度的梯度下降变体" },
        { term: "overfitting", pos: "n.", phonetic: "/ˌəʊvəˈfɪtɪŋ/", definition: "过拟合 - 模型过于复杂，在训练数据上表现良好但泛化能力差" },
        { term: "underfitting", pos: "n.", phonetic: "/ˌʌndəˈfɪtɪŋ/", definition: "欠拟合 - 模型过于简单，无法捕获数据中的模式" },
        { term: "hyperparameter", pos: "n.", phonetic: "/ˌhaɪpəˈpærəmɪtə/", definition: "超参数 - 在训练前设置的模型参数，如学习率" },
        { term: "logistic function", pos: "n.", phonetic: "/ləˈdʒɪstɪk ˈfʌŋkʃn/", definition: "逻辑函数 - 将输入映射到0到1之间概率值的S形函数" },
        { term: "decision boundary", pos: "n.", phonetic: "/dɪˈsɪʒn ˈbaʊndəri/", definition: "决策边界 - 分类器用来划分不同类别的边界" },
        { term: "iteration", pos: "n.", phonetic: "/ˌɪtəˈreɪʃn/", definition: "迭代 - 重复执行某个过程直到满足特定条件" },
        { term: "convergence", pos: "n.", phonetic: "/kənˈvɜːdʒəns/", definition: "收敛 - 算法逐渐接近解决方案的过程" },
        { term: "convex", pos: "adj.", phonetic: "/ˈkɒnveks/", definition: "凸的 - 描述一种特殊形状的函数，保证找到全局最小值" },
        { term: "cubic", pos: "adj.", phonetic: "/ˈkjuːbɪk/", definition: "立方的 - 与三次方相关的" },
        { term: "divergence", pos: "n.", phonetic: "/daɪˈvɜːdʒəns/", definition: "发散 - 算法远离解决方案的现象" },
        { term: "elongated", pos: "adj.", phonetic: "/ˈiːlɒŋɡeɪtɪd/", definition: "细长的 - 在一个方向上延伸得比另一个方向长" },
        { term: "derivative", pos: "n.", phonetic: "/dɪˈrɪvətɪv/", definition: "导数 - 函数变化率的数学表示" },
        { term: "generalize", pos: "v.", phonetic: "/ˈdʒenərəlaɪz/", definition: "泛化 - 模型应用于新数据的能力" },
        { term: "plateau", pos: "n.", phonetic: "/ˈplætəʊ/", definition: "高原，平稳期 - 梯度下降中进展停滞的区域" },
        { term: "vectors", pos: "n.", phonetic: "/ˈvektəz/", definition: "向量 - 具有大小和方向的数学量" },
        { term: "matrices", pos: "n.", phonetic: "/ˈmeɪtrɪsiːz/", definition: "矩阵 - 数字或符号排列成的矩形阵列" },
        { term: "explicit", pos: "adj.", phonetic: "/ɪkˈsplɪsɪt/", definition: "明确的 - 清晰表达的，不含糊的" },
        { term: "computation", pos: "n.", phonetic: "/ˌkɒmpjʊˈteɪʃn/", definition: "计算 - 使用计算机或数学方法解决问题的过程" },
        { term: "optimization", pos: "n.", phonetic: "/ˌɒptɪmaɪˈzeɪʃn/", definition: "优化 - 寻找最佳解决方案的过程" },
        { term: "probabilistic", pos: "adj.", phonetic: "/ˌprɒbəbɪˈlɪstɪk/", definition: "概率的 - 基于或关于概率的" },
        { term: "momentum", pos: "n.", phonetic: "/məˈmentəm/", definition: "动量 - 帮助梯度下降加速收敛的技术" },
        { term: "numerical", pos: "adj.", phonetic: "/njuːˈmerɪkl/", definition: "数值的 - 与数字相关的，用数量表示的" },
        { term: "complexity", pos: "n.", phonetic: "/kəmˈpleksɪti/", definition: "复杂性 - 系统或模型的复杂程度" },
        { term: "substantial", pos: "adj.", phonetic: "/səbˈstænʃl/", definition: "实质的 - 相当大的或重要的" },
        { term: "vector", pos: "n.", phonetic: "/ˈvektə/", definition: "向量 - 具有大小和方向的量" },
        { term: "function", pos: "n.", phonetic: "/ˈfʌŋkʃn/", definition: "函数 - 输入和输出之间的映射关系" },
        { term: "approximation", pos: "n.", phonetic: "/əˌprɒksɪˈmeɪʃn/", definition: "近似 - 接近但不完全准确的表示" },
        { term: "robust", pos: "adj.", phonetic: "/rəˈbʌst/", definition: "健壮的 - 能够处理变化和错误的系统特性" },
        { term: "exponential", pos: "adj.", phonetic: "/ˌekspəˈnenʃl/", definition: "指数的 - 关于指数或指数函数的" },
        { term: "inference", pos: "n.", phonetic: "/ˈɪnfərəns/", definition: "推断 - 从证据和推理得出结论的过程" }
    ],
    
    // 第四讲内容
    4: [
        { term: "Bias/Variance Tradeoff", pos: "n.", phonetic: "/ˈbaɪəs ˈvɛəriəns ˈtreɪdɒf/", definition: "偏差/方差权衡 - 模型复杂度与泛化能力之间的平衡" },
        { term: "Generalisation error", pos: "n.", phonetic: "/ˌdʒɛnərəlaɪˈzeɪʃən ˈɛrə/", definition: "泛化误差 - 模型在新数据上的预期误差" },
        { term: "Underfitting", pos: "n.", phonetic: "/ˌʌndəˈfɪtɪŋ/", definition: "欠拟合 - 模型过于简单，无法捕获数据中的模式" },
        { term: "Overfitting", pos: "n.", phonetic: "/ˌəʊvəˈfɪtɪŋ/", definition: "过拟合 - 模型过于复杂，捕获了数据中的噪声" },
        { term: "Regularisation", pos: "n.", phonetic: "/ˌrɛɡjʊləraɪˈzeɪʃən/", definition: "正则化 - 通过添加惩罚项来控制模型复杂度的技术" },
        { term: "Hyperparameters", pos: "n.", phonetic: "/ˌhaɪpəˈpærəmɪtəz/", definition: "超参数 - 在训练前设置的模型参数" },
        { term: "Cross-validation", pos: "n.", phonetic: "/krɒs vælɪˈdeɪʃən/", definition: "交叉验证 - 通过多次拆分数据来评估模型性能的方法" },
        { term: "Grid Search", pos: "n.", phonetic: "/ɡrɪd sɜːtʃ/", definition: "网格搜索 - 寻找最佳超参数的方法" },
        { term: "Early Stopping", pos: "n.", phonetic: "/ˈɜːli ˈstɒpɪŋ/", definition: "早停法 - 在过拟合发生前停止训练的技术" },
        { term: "Ridge Regression", pos: "n.", phonetic: "/rɪdʒ rɪˈɡrɛʃən/", definition: "岭回归 - 使用L2正则化的线性回归" },
        { term: "Lasso Regression", pos: "n.", phonetic: "/ˈlæsəʊ rɪˈɡrɛʃən/", definition: "套索回归 - 使用L1正则化的线性回归" },
        { term: "Elastic Net", pos: "n.", phonetic: "/ɪˈlæstɪk nɛt/", definition: "弹性网络 - 结合L1和L2正则化的回归方法" },
        { term: "Softmax Regression", pos: "n.", phonetic: "/ˈsɒftmæks rɪˈɡrɛʃən/", definition: "Softmax回归 - 处理多类别分类的回归模型" },
        { term: "k-Nearest Neighbours", pos: "n.", phonetic: "/keɪ ˈnɪərɪst ˈneɪbəz/", definition: "k近邻算法 - 基于相似度的分类和回归算法" },
        { term: "Distance metric", pos: "n.", phonetic: "/ˈdɪstəns ˈmɛtrɪk/", definition: "距离度量 - 衡量样本之间相似度的方法" },
        { term: "Minkowski distance", pos: "n.", phonetic: "/mɪŋˈkɒfski ˈdɪstəns/", definition: "闵可夫斯基距离 - 距离度量的一种泛化形式" },
        { term: "Multiclass Classification", pos: "n.", phonetic: "/ˌmʌltiˈklɑːs ˌklæsɪfɪˈkeɪʃn/", definition: "多类分类 - 将样本分类到三个以上类别的任务" },
        { term: "Multilabel Classification", pos: "n.", phonetic: "/ˌmʌltiˈleɪbl ˌklæsɪfɪˈkeɪʃn/", definition: "多标签分类 - 每个样本可以属于多个类别的分类" },
        { term: "Multioutput-Multiclass Classification", pos: "n.", phonetic: "/ˌmʌltiˈaʊtpʊt mʌltiˈklɑːs ˌklæsɪfɪˈkeɪʃn/", definition: "多输出多类分类 - 具有多个多类别目标变量的分类问题" },
        { term: "Assumption", pos: "n.", phonetic: "/əˈsʌmpʃən/", definition: "假设 - 被认为是真实但可能未经验证的事情" },
        { term: "Excessive", pos: "adj.", phonetic: "/ɪkˈsɛsɪv/", definition: "过度的 - 超出必要或正常范围的" },
        { term: "Sensitivity", pos: "n.", phonetic: "/ˌsɛnsɪˈtɪvɪti/", definition: "敏感性 - 对变化作出反应的程度" },
        { term: "Variation", pos: "n.", phonetic: "/vɛəriˈeɪʃən/", definition: "变化 - 从标准形式或位置的偏离" },
        { term: "Irreducible", pos: "adj.", phonetic: "/ˌɪrɪˈdjuːsəbl/", definition: "不可约的 - 不能被降低或简化的" },
        { term: "Constraints", pos: "n.", phonetic: "/kənˈstreɪnts/", definition: "约束 - 限制或条件" },
        { term: "Via", pos: "prep.", phonetic: "/ˈvaɪə/", definition: "通过 - 借助...的方式" },
        { term: "Estimation", pos: "n.", phonetic: "/ˌɛstɪˈmeɪʃən/", definition: "估计 - 对数量或值的近似计算" },
        { term: "Normalized", pos: "adj.", phonetic: "/ˈnɔːməlaɪzd/", definition: "归一化的 - 调整为标准形式或比例的" },
        { term: "Exponential", pos: "adj.", phonetic: "/ˌɛkspəˈnenʃəl/", definition: "指数的 - 以指数方式增长或减少的" },
        { term: "Coefficient", pos: "n.", phonetic: "/ˌkəʊɪˈfɪʃənt/", definition: "系数 - 在方程中与变量相乘的数" },
        { term: "Partition", pos: "n.", phonetic: "/pɑːˈtɪʃən/", definition: "分区 - 将整体分成部分的过程" },
        { term: "Aggregate", pos: "v.", phonetic: "/ˈæɡrɪɡeɪt/", definition: "聚合 - 将不同的元素组合成一个整体" },
        { term: "Vicinity", pos: "n.", phonetic: "/vɪˈsɪnɪti/", definition: "附近 - 靠近某个位置的区域" },
        { term: "Density", pos: "n.", phonetic: "/ˈdɛnsɪti/", definition: "密度 - 单位空间内的物质量" },
        { term: "Crucial", pos: "adj.", phonetic: "/ˈkruːʃəl/", definition: "关键的 - 具有决定性影响的" },
        { term: "Duels", pos: "n.", phonetic: "/ˈdjuːəlz/", definition: "决斗 - 两个人或团体之间的竞争或对抗" },
        { term: "Intensive", pos: "adj.", phonetic: "/ɪnˈtɛnsɪv/", definition: "密集的 - 程度高或集中的" },
        { term: "Attribute", pos: "n.", phonetic: "/ˈætrɪbjuːt/", definition: "属性 - 事物固有的特质或特征" },
        { term: "Strictly", pos: "adv.", phonetic: "/ˈstrɪktli/", definition: "严格地 - 精确地遵循规则或定义" }
    ]
}; 