// 各讲义的专业术语和四级词汇
const lectureData = {
    // 第一讲内容 - 模板：{ term: "词汇", pos: "词性", phonetic: "音标", definition: "定义" }
    1: [
        { term: "Machine Learning (ML)", pos: "n.", phonetic: "/məˈʃiːn ˈlɜːnɪŋ/", definition: "机器学习 - 让计算机从数据中学习而不需要明确编程的科学" },
        { term: "Inductive learning", pos: "n.", phonetic: "/ɪnˈdʌktɪv ˈlɜːnɪŋ/", definition: "归纳学习 - 从特定样例集中获得通用结论的逻辑推理形式" },
        { term: "Supervised learning", pos: "n.", phonetic: "/ˈsuːpəvaɪzd ˈlɜːnɪŋ/", definition: "监督学习 - 使用已标记的训练数据来学习输入到输出的映射" },
        { term: "Unsupervised learning", pos: "n.", phonetic: "/ˌʌnˈsuːpəvaɪzd ˈlɜːnɪŋ/", definition: "无监督学习 - 使用未标记的数据发现其中的模式或结构" },
        { term: "Classification", pos: "n.", phonetic: "/ˌklæsɪfɪˈkeɪʃn/", definition: "分类 - 将输入数据划分到已定义的类别中的任务" },
        { term: "Regression", pos: "n.", phonetic: "/rɪˈɡreʃn/", definition: "回归 - 预测连续数值输出的任务" },
        { term: "Training set", pos: "n.", phonetic: "/ˈtreɪnɪŋ set/", definition: "训练集 - 用于训练机器学习模型的数据集" },
        { term: "Test set", pos: "n.", phonetic: "/test set/", definition: "测试集 - 用于评估模型性能的独立数据集" },
        { term: "Validation set", pos: "n.", phonetic: "/ˌvælɪˈdeɪʃn set/", definition: "验证集 - 用于调整超参数的额外数据集" },
        { term: "Attribute/Feature", pos: "n.", phonetic: "/ˈætrɪbjuːt/ˈfiːtʃə/", definition: "属性/特征 - 描述实例特征的变量" },
        { term: "Instance/Example", pos: "n.", phonetic: "/ˈɪnstəns/ɪɡˈzɑːmpl/", definition: "实例/样本 - 描述对象的属性值元组" },
        { term: "Label/Target feature", pos: "n.", phonetic: "/ˈleɪbl/ˈtɑːɡɪt ˈfiːtʃə/", definition: "标签/目标特征 - 描述要预测的现象的特殊属性" },
        { term: "Data set", pos: "n.", phonetic: "/ˈdeɪtə set/", definition: "数据集 - 由实例及其相应属性值和标签组成的集合" },
        { term: "Descriptive features", pos: "n.", phonetic: "/dɪˈskrɪptɪv ˈfiːtʃəz/", definition: "描述性特征 - 用于描述实例的属性" },
        { term: "Target function", pos: "n.", phonetic: "/ˈtɑːɡɪt ˈfʌŋkʃn/", definition: "目标函数 - 从输入空间到输出空间的理想映射" },
        { term: "Hypothesis space", pos: "n.", phonetic: "/haɪˈpɒθəsɪs speɪs/", definition: "假设空间 - 学习算法可以考虑的候选函数集合" },
        { term: "Learning model", pos: "n.", phonetic: "/ˈlɜːnɪŋ ˈmɒdl/", definition: "学习模型 - 由学习算法和假设集组成的系统" },
        { term: "Classifier", pos: "n.", phonetic: "/ˈklæsɪfaɪə/", definition: "分类器 - 将输入分配到预定义类别的模型" },
        { term: "Instance-based learning", pos: "n.", phonetic: "/ˈɪnstəns beɪst ˈlɜːnɪŋ/", definition: "基于实例的学习 - 通过比较新实例与学习到的实例来泛化" },
        { term: "Model-based learning", pos: "n.", phonetic: "/ˈmɒdl beɪst ˈlɜːnɪŋ/", definition: "基于模型的学习 - 从训练样本构建模型并用于预测" },
        { term: "Clustering", pos: "n.", phonetic: "/ˈklʌstərɪŋ/", definition: "聚类 - 将数据分组到相似实例集合的无监督方法" },
        { term: "K-means clustering", pos: "n.", phonetic: "/keɪ miːnz ˈklʌstərɪŋ/", definition: "K均值聚类 - 将数据分为K个聚类的算法" },
        { term: "DBSCAN", pos: "n.", phonetic: "/diː biː skæn/", definition: "基于密度的空间聚类 - 根据密度定义区域发现聚类的算法" },
        { term: "Hierarchical Cluster Analysis (HCA)", pos: "n.", phonetic: "/haɪəˈrɑːkɪkl ˈklʌstə əˈnæləsɪs/", definition: "层次聚类分析 - 创建聚类层次结构的方法" },
        { term: "Principal Component Analysis (PCA)", pos: "n.", phonetic: "/ˈprɪnsəpl kəmˈpəʊnənt əˈnæləsɪs/", definition: "主成分分析 - 降低数据维度同时保留变异的技术" },
        { term: "Dimensionality reduction", pos: "n.", phonetic: "/daɪˌmenʃəˈnælɪti rɪˈdʌkʃn/", definition: "降维 - 减少数据特征数量的过程" },
        { term: "Anomaly detection", pos: "n.", phonetic: "/əˈnɒməli dɪˈtekʃn/", definition: "异常检测 - 识别异常实例或离群点的技术" },
        { term: "Generalisation error", pos: "n.", phonetic: "/ˌdʒenərəlaɪˈzeɪʃn ˈerə/", definition: "泛化误差 - 模型在新数据上的错误率" },
        { term: "Out-of-sample error", pos: "n.", phonetic: "/aʊt əv ˈsɑːmpl ˈerə/", definition: "样本外误差 - 模型在训练集之外数据上的表现" },
        { term: "Hyperparameter", pos: "n.", phonetic: "/ˌhaɪpəˈpærəmɪtə/", definition: "超参数 - 学习算法的配置值，不通过训练过程学习" },
        { term: "Overfitting", pos: "n.", phonetic: "/ˌəʊvəˈfɪtɪŋ/", definition: "过拟合 - 模型过度适应训练数据细节而无法泛化的现象" },
        { term: "Underfitting", pos: "n.", phonetic: "/ˌʌndəˈfɪtɪŋ/", definition: "欠拟合 - 模型过于简单，无法捕获数据模式的现象" },
        { term: "Online learning", pos: "n.", phonetic: "/ˈɒnlaɪn ˈlɜːnɪŋ/", definition: "在线学习 - 能够增量学习的系统" },
        { term: "Batch learning", pos: "n.", phonetic: "/bætʃ ˈlɜːnɪŋ/", definition: "批量学习 - 一次性使用所有可用数据训练的系统" },
        { term: "Association rule learning", pos: "n.", phonetic: "/əˌsəʊsɪˈeɪʃn ruːl ˈlɜːnɪŋ/", definition: "关联规则学习 - 发现变量之间关系的方法" },
        { term: "Decision boundary", pos: "n.", phonetic: "/dɪˈsɪʒn ˈbaʊndəri/", definition: "决策边界 - 分类算法中划分不同类别的边界" },
        { term: "Locally-Linear Embedding (LLE)", pos: "n.", phonetic: "/ˈləʊkəli ˈlɪnɪə ɪmˈbedɪŋ/", definition: "局部线性嵌入 - 用于降维的非线性技术" },
        { term: "t-distributed Stochastic Neighbor Embedding (t-SNE)", pos: "n.", phonetic: "/tiː dɪsˈtrɪbjuːtɪd stəˈkæstɪk ˈneɪbə ɪmˈbedɪŋ/", definition: "t分布随机邻域嵌入 - 数据可视化降维技术" },
        { term: "Apriori algorithm", pos: "n.", phonetic: "/eɪpriˈɔːri ˈælɡərɪðəm/", definition: "Apriori算法 - 用于关联规则学习的经典算法" },
        { term: "Eclat algorithm", pos: "n.", phonetic: "/ɪˈklæt ˈælɡərɪðəm/", definition: "Eclat算法 - 高效的关联规则挖掘算法" },
        { term: "Reinforcement learning", pos: "n.", phonetic: "/ˌriːɪnˈfɔːsmənt ˈlɜːnɪŋ/", definition: "强化学习 - 通过与环境交互学习最优策略的机器学习方法" },
        { term: "Semi-supervised learning", pos: "n.", phonetic: "/ˌsemiˈsuːpəvaɪzd ˈlɜːnɪŋ/", definition: "半监督学习 - 结合少量标记数据和大量未标记数据的学习方法" },
        { term: "Acquisition", pos: "n.", phonetic: "/ˌækwɪˈzɪʃn/", definition: "获取 - 获得或收集数据或知识的过程" },
        { term: "Inference", pos: "n.", phonetic: "/ˈɪnfərəns/", definition: "推理 - 从已知信息或证据得出结论的过程" },
        { term: "Generic", pos: "adj.", phonetic: "/dʒəˈnerɪk/", definition: "通用的 - 适用于整个类别而非特定个体的" },
        { term: "Conclusion", pos: "n.", phonetic: "/kənˈkluːʒn/", definition: "结论 - 通过推理得出的判断或决定" },
        { term: "Particular", pos: "adj.", phonetic: "/pəˈtɪkjələ/", definition: "特定的 - 与其他事物区别的特殊的或明确的" },
        { term: "Phenomenon", pos: "n.", phonetic: "/fəˈnɒmɪnən/", definition: "现象 - 可观察到的事件或事实" },
        { term: "Tuple", pos: "n.", phonetic: "/ˈtjuːpl/", definition: "元组 - 有序的元素集合" },
        { term: "Vector", pos: "n.", phonetic: "/ˈvektə/", definition: "向量 - 具有大小和方向的量" },
        { term: "Associate", pos: "v.", phonetic: "/əˈsəʊʃɪeɪt/", definition: "关联 - 将事物或概念连接起来" },
        { term: "Construct", pos: "v.", phonetic: "/kənˈstrʌkt/", definition: "构建 - 创建或形成某物" },
        { term: "Automate", pos: "v.", phonetic: "/ˈɔːtəmeɪt/", definition: "自动化 - 使过程或系统自动运行" },
        { term: "Evaluate", pos: "v.", phonetic: "/ɪˈvæljueɪt/", definition: "评估 - 确定某物的价值或重要性" },
        { term: "Incrementally", pos: "adv.", phonetic: "/ˌɪnkrəˈmentəli/", definition: "递增地 - 以渐进的方式" },
        { term: "Generalise", pos: "v.", phonetic: "/ˈdʒenərəlaɪz/", definition: "泛化 - 从特定情况中推导出普遍原则" },
        { term: "Threshold", pos: "n.", phonetic: "/ˈθreʃəʊld/", definition: "阈值 - 触发效应或行动的临界点" },
        { term: "Coordinate", pos: "n.", phonetic: "/kəʊˈɔːdɪnət/", definition: "坐标 - 确定点位置的一组数值" },
        { term: "Candidate", pos: "n.", phonetic: "/ˈkændɪdət/", definition: "候选 - 被考虑接受位置或奖励的人或物" },
        { term: "Insufficient", pos: "adj.", phonetic: "/ˌɪnsəˈfɪʃnt/", definition: "不足的 - 数量或质量不够满足需求的" },
        { term: "Representative", pos: "adj.", phonetic: "/ˌreprɪˈzentətɪv/", definition: "代表性的 - 典型的或能代表整体的" },
        { term: "Relevant", pos: "adj.", phonetic: "/ˈreləvənt/", definition: "相关的 - 与当前主题或情况有关的" },
        { term: "Irrelevant", pos: "adj.", phonetic: "/ɪˈreləvənt/", definition: "不相关的 - 与当前主题或情况无关的" },
        { term: "Explicit", pos: "adj.", phonetic: "/ɪkˈsplɪsɪt/", definition: "明确的 - 清晰表达且不留歧义的" },
        { term: "Parameter", pos: "n.", phonetic: "/pəˈræmɪtə/", definition: "参数 - 定义系统特征或行为的数值" },
        { term: "Bias", pos: "n.", phonetic: "/ˈbaɪəs/", definition: "偏差 - 对某一观点或结果的系统性倾向" },
        { term: "Criteria", pos: "n.", phonetic: "/kraɪˈtɪəriə/", definition: "标准 - 用来判断或决策的原则或标准" },
        { term: "Exclusive", pos: "adj.", phonetic: "/ɪkˈskluːsɪv/", definition: "排他的 - 不包含其他事物或限制参与的" },
        { term: "Objective", pos: "n.", phonetic: "/əbˈdʒektɪv/", definition: "目标 - 希望实现的结果或目的" },
        { term: "Abnormal", pos: "adj.", phonetic: "/æbˈnɔːml/", definition: "异常的 - 偏离正常或预期的" },
        { term: "Hierarchy", pos: "n.", phonetic: "/ˈhaɪərɑːki/", definition: "层次结构 - 按级别或重要性排序的系统" },
        { term: "Stochastic", pos: "adj.", phonetic: "/stəˈkæstɪk/", definition: "随机的 - 包含随机变量或概率的" },
        { term: "Density", pos: "n.", phonetic: "/ˈdensəti/", definition: "密度 - 单位体积或空间内的质量或数量" },
        { term: "Polluted", pos: "adj.", phonetic: "/pəˈluːtɪd/", definition: "受污染的 - 被有害物质污染的" },
        { term: "Visualization", pos: "n.", phonetic: "/ˌvɪʒuəlaɪˈzeɪʃn/", definition: "可视化 - 将数据或概念以图形方式呈现" },
        { term: "Embedded", pos: "adj.", phonetic: "/ɪmˈbedɪd/", definition: "嵌入的 - 固定或包含在更大结构中的" },
        { term: "Embedding", pos: "n.", phonetic: "/ɪmˈbedɪŋ/", definition: "嵌入 - 将对象插入或包含在介质中的过程" }
    ],
    
    // 第二讲内容
    2: [
        { term: "Machine Learning", pos: "n.", phonetic: "/məˈʃiːn ˈlɜːnɪŋ/", definition: "机器学习 - 计算机系统通过数据学习和改进性能的科学" },
        { term: "Jupyter Notebook", pos: "n.", phonetic: "/ˈdʒuːpɪtər ˈnoʊtbʊk/", definition: "Jupyter笔记本 - 一种交互式编程环境，允许创建和共享包含代码、文本和可视化的文档" },
        { term: "Scikit-Learn", pos: "n.", phonetic: "/ˈsaɪkɪt lɜːn/", definition: "Scikit-Learn - Python中用于机器学习的流行库" },
        { term: "TensorFlow", pos: "n.", phonetic: "/ˈtɛnsərfloʊ/", definition: "TensorFlow - Google开发的开源机器学习框架" },
        { term: "Learning model", pos: "n.", phonetic: "/ˈlɜːnɪŋ ˈmɒdl/", definition: "学习模型 - 从数据中学习并做出预测的算法" },
        { term: "Synthetic data set", pos: "n.", phonetic: "/sɪnˈθɛtɪk ˈdeɪtə sɛt/", definition: "合成数据集 - 人工生成而非真实收集的数据集" },
        { term: "Environment", pos: "n.", phonetic: "/ɪnˈvaɪrənmənt/", definition: "环境 - 在这里指Python的虚拟环境，用于管理软件包和依赖项" },
        { term: "Google Colaboratory", pos: "n.", phonetic: "/ˈɡuːɡəl kəˈlæbərətɔːri/", definition: "Google协作实验室 - Google提供的基于云的Jupyter笔记本环境" },
        { term: "Virtual Machines", pos: "n.", phonetic: "/ˈvɜːtʃuəl məˈʃiːnz/", definition: "虚拟机 - 模拟计算机系统的软件" },
        { term: "Install", pos: "v.", phonetic: "/ɪnˈstɔːl/", definition: "安装 - 将软件程序放置到计算机上使其可运行" },
        { term: "Responsible", pos: "adj.", phonetic: "/rɪˈspɒnsəbl/", definition: "负责的 - 对某事或某人有义务或控制权" },
        { term: "Experiment", pos: "n.", phonetic: "/ɪkˈspɛrɪmənt/", definition: "实验 - 通过测试探索或验证想法的过程" },
        { term: "Implement", pos: "v.", phonetic: "/ˈɪmplɪmɛnt/", definition: "实施、实现 - 把计划、想法等付诸实践" },
        { term: "Assuming", pos: "v.", phonetic: "/əˈsjuːmɪŋ/", definition: "假设 - 认为某事是真实的，但没有证据" },
        { term: "Assignment", pos: "n.", phonetic: "/əˈsaɪnmənt/", definition: "作业、任务 - 分配给学生的工作或项目" },
        { term: "Documentation", pos: "n.", phonetic: "/ˌdɒkjʊmɛnˈteɪʃn/", definition: "文档 - 提供信息和说明的材料" },
        { term: "Resources", pos: "n.", phonetic: "/rɪˈzɔːsɪz/", definition: "资源 - 可用于帮助完成任务的材料或信息" },
        { term: "Synthetic", pos: "adj.", phonetic: "/sɪnˈθɛtɪk/", definition: "合成的 - 人工制造而非自然产生的" },
        { term: "Issue", pos: "n.", phonetic: "/ˈɪʃuː/", definition: "问题、议题 - 需要解决或讨论的事情" },
        { term: "Environment", pos: "n.", phonetic: "/ɪnˈvaɪrənmənt/", definition: "环境 - 在编程中，指特定的软件配置" },
        { term: "Download", pos: "v.", phonetic: "/ˌdaʊnˈloʊd/", definition: "下载 - 从互联网将数据传输到本地设备" },
        { term: "Properly", pos: "adv.", phonetic: "/ˈprɒpəli/", definition: "正确地、适当地 - 以正确或合适的方式" },
        { term: "Necessary", pos: "adj.", phonetic: "/ˈnɛsəsəri/", definition: "必要的 - 需要的，不可避免的" },
        { term: "Available", pos: "adj.", phonetic: "/əˈveɪləbl/", definition: "可用的 - 能够被获取或使用的" }
    ],
    
    // 第三讲内容
    3: [
        { term: "Linear Regression", pos: "n.", phonetic: "/ˈlɪniər rɪˈɡreʃn/", definition: "线性回归 - 一种通过计算输入特征的加权和来进行预测的线性模型" },
        { term: "Gradient Descent", pos: "n.", phonetic: "/ˈɡreɪdiənt dɪˈsent/", definition: "梯度下降 - 一种通过迭代调整参数以最小化成本函数的优化算法" },
        { term: "Polynomial Regression", pos: "n.", phonetic: "/ˌpɒliˈnoʊmiəl rɪˈɡreʃn/", definition: "多项式回归 - 使用多项式函数进行拟合的回归分析方法" },
        { term: "Learning Curves", pos: "n.", phonetic: "/ˈlɜːrnɪŋ kɜːrvz/", definition: "学习曲线 - 显示模型在训练集和验证集上性能随训练集大小变化的图表" },
        { term: "Regularised Linear Models", pos: "n.", phonetic: "/ˈreɡjʊləraɪzd ˈlɪniər ˈmɒdlz/", definition: "正则化线性模型 - 添加惩罚项以避免过拟合的线性模型" },
        { term: "Logistic Regression", pos: "n.", phonetic: "/ləˈdʒɪstɪk rɪˈɡreʃn/", definition: "逻辑回归 - 用于估计实例属于特定类别概率的分类算法" },
        { term: "Bias term", pos: "n.", phonetic: "/ˈbaɪəs tɜːrm/", definition: "偏置项 - 线性模型中的常数项，也称为截距项" },
        { term: "Feature weights", pos: "n.", phonetic: "/ˈfiːtʃər weɪts/", definition: "特征权重 - 线性模型中各特征的系数" },
        { term: "Mean Squared Error", pos: "n.", phonetic: "/miːn skweərd ˈerər/", definition: "均方误差 - 回归模型常用的性能评估指标" },
        { term: "Residual Sum of Squares", pos: "n.", phonetic: "/rɪˈzɪdjuəl sʌm əv skweərz/", definition: "残差平方和 - 实际值与预测值差的平方和" },
        { term: "Normal Equation", pos: "n.", phonetic: "/ˈnɔːrməl ɪˈkweɪʒn/", definition: "正规方程 - 一种直接计算线性回归最优参数的数学方程" },
        { term: "Cost function", pos: "n.", phonetic: "/kɒst ˈfʌŋkʃn/", definition: "成本函数 - 衡量模型性能的函数，训练目标是最小化该函数" },
        { term: "Partial derivative", pos: "n.", phonetic: "/ˈpɑːrʃəl dɪˈrɪvətɪv/", definition: "偏导数 - 多变量函数对某一变量的导数" },
        { term: "Gradient vector", pos: "n.", phonetic: "/ˈɡreɪdiənt ˈvektər/", definition: "梯度向量 - 包含函数所有偏导数的向量" },
        { term: "Random initialization", pos: "n.", phonetic: "/ˈrændəm ɪˌnɪʃəlaɪˈzeɪʃn/", definition: "随机初始化 - 用随机值初始化模型参数的过程" },
        { term: "Learning rate", pos: "n.", phonetic: "/ˈlɜːrnɪŋ reɪt/", definition: "学习率 - 控制梯度下降步长的超参数" },
        { term: "Batch GD", pos: "n.", phonetic: "/bætʃ dʒiː diː/", definition: "批量梯度下降 - 使用整个训练集计算梯度的梯度下降变体" },
        { term: "Stochastic GD", pos: "n.", phonetic: "/stəˈkæstɪk dʒiː diː/", definition: "随机梯度下降 - 每步基于单个随机实例计算梯度的梯度下降变体" },
        { term: "Mini-batch GD", pos: "n.", phonetic: "/ˈmɪni bætʃ dʒiː diː/", definition: "小批量梯度下降 - 基于小随机样本集计算梯度的梯度下降变体" },
        { term: "Overfitting", pos: "n.", phonetic: "/ˌoʊvərˈfɪtɪŋ/", definition: "过拟合 - 模型过于复杂，在训练数据上表现良好但泛化能力差" },
        { term: "Underfitting", pos: "n.", phonetic: "/ˌʌndərˈfɪtɪŋ/", definition: "欠拟合 - 模型过于简单，无法捕获数据中的模式" },
        { term: "Hyperparameter", pos: "n.", phonetic: "/ˌhaɪpərˈpærəmɪtər/", definition: "超参数 - 在训练前设置的模型参数，如学习率" },
        { term: "Logistic function", pos: "n.", phonetic: "/ləˈdʒɪstɪk ˈfʌŋkʃn/", definition: "逻辑函数 - 将输入映射到0到1之间概率值的S形函数" },
        { term: "Decision boundary", pos: "n.", phonetic: "/dɪˈsɪʒn ˈbaʊndəri/", definition: "决策边界 - 分类器用来划分不同类别的边界" },
        { term: "Iteration", pos: "n.", phonetic: "/ˌɪtəˈreɪʃn/", definition: "迭代 - 重复执行某个过程直到满足特定条件" },
        { term: "Convergence", pos: "n.", phonetic: "/kənˈvɜːrdʒəns/", definition: "收敛 - 算法逐渐接近解决方案的过程" },
        { term: "Convex", pos: "adj.", phonetic: "/ˈkɒnveks/", definition: "凸的 - 描述一种特殊形状的函数，保证找到全局最小值" },
        { term: "Cubic", pos: "adj.", phonetic: "/ˈkjuːbɪk/", definition: "立方的 - 与三次方相关的" },
        { term: "Divergence", pos: "n.", phonetic: "/daɪˈvɜːrdʒəns/", definition: "发散 - 算法远离解决方案的现象" },
        { term: "Elongated", pos: "adj.", phonetic: "/ˈiːlɒŋɡeɪtɪd/", definition: "细长的 - 在一个方向上延伸得比另一个方向长" },
        { term: "Derivative", pos: "n.", phonetic: "/dɪˈrɪvətɪv/", definition: "导数 - 函数变化率的数学表示" },
        { term: "Generalize", pos: "v.", phonetic: "/ˈdʒenərəlaɪz/", definition: "泛化 - 模型应用于新数据的能力" },
        { term: "Plateau", pos: "n.", phonetic: "/plæˈtoʊ/", definition: "高原，平稳期 - 梯度下降中进展停滞的区域" },
        { term: "Vectors", pos: "n.", phonetic: "/ˈvektərz/", definition: "向量 - 具有大小和方向的数学量" },
        { term: "Matrices", pos: "n.", phonetic: "/ˈmeɪtrɪsiːz/", definition: "矩阵 - 数字或符号排列成的矩形阵列" },
        { term: "Explicit", pos: "adj.", phonetic: "/ɪkˈsplɪsɪt/", definition: "明确的 - 清晰表达的，不含糊的" },
        { term: "Computation", pos: "n.", phonetic: "/ˌkɒmpjuˈteɪʃn/", definition: "计算 - 使用计算机或数学方法解决问题的过程" },
        { term: "Optimization", pos: "n.", phonetic: "/ˌɒptɪmaɪˈzeɪʃn/", definition: "优化 - 寻找最佳解决方案的过程" },
        { term: "Probabilistic", pos: "adj.", phonetic: "/ˌprɒbəbɪˈlɪstɪk/", definition: "概率的 - 基于或关于概率的" },
        { term: "Momentum", pos: "n.", phonetic: "/məˈmentəm/", definition: "动量 - 帮助梯度下降加速收敛的技术" },
        { term: "Numerical", pos: "adj.", phonetic: "/njuːˈmerɪkəl/", definition: "数值的 - 与数字相关的，用数量表示的" },
        { term: "Complexity", pos: "n.", phonetic: "/kəmˈpleksɪti/", definition: "复杂性 - 系统或模型的复杂程度" },
        { term: "Substantial", pos: "adj.", phonetic: "/səbˈstænʃl/", definition: "实质的 - 相当大的或重要的" },
        { term: "Vector", pos: "n.", phonetic: "/ˈvektər/", definition: "向量 - 具有大小和方向的量" },
        { term: "Function", pos: "n.", phonetic: "/ˈfʌŋkʃn/", definition: "函数 - 输入和输出之间的映射关系" },
        { term: "Approximation", pos: "n.", phonetic: "/əˌprɒksɪˈmeɪʃn/", definition: "近似 - 接近但不完全准确的表示" },
        { term: "Robust", pos: "adj.", phonetic: "/rəʊˈbʌst/", definition: "健壮的 - 能够处理变化和错误的系统特性" },
        { term: "Exponential", pos: "adj.", phonetic: "/ˌekspəˈnenʃl/", definition: "指数的 - 关于指数或指数函数的" },
        { term: "Inference", pos: "n.", phonetic: "/ˈɪnfərəns/", definition: "推断 - 从证据和推理得出结论的过程" }
    ],
    
    // 第四讲内容
    4: [
        { term: "Bias/Variance Tradeoff", pos: "n.", phonetic: "/ˈbaɪəs ˈvɛəriəns ˈtreɪdɒf/", definition: "偏差/方差权衡 - 机器学习模型中的一个基本概念，涉及模型复杂度、欠拟合和过拟合之间的平衡" },
        { term: "Generalisation error", pos: "n.", phonetic: "/ˌdʒɛnərəlaɪˈzeɪʃən ˈɛrə/", definition: "泛化误差 - 模型在未见过的数据上的预测误差" },
        { term: "Underfitting", pos: "n.", phonetic: "/ˌʌndəˈfɪtɪŋ/", definition: "欠拟合 - 模型太简单，无法学习数据的基本结构" },
        { term: "Overfitting", pos: "n.", phonetic: "/ˌəʊvəˈfɪtɪŋ/", definition: "过拟合 - 模型过于复杂，捕捉了训练数据中的噪声而非真实关系" },
        { term: "Regularisation", pos: "n.", phonetic: "/ˌrɛɡjʊləraɪˈzeɪʃən/", definition: "正则化 - 通过对模型添加约束来防止过拟合的技术" },
        { term: "Hyperparameters", pos: "n.", phonetic: "/ˌhaɪpərˈpærəmɪtəz/", definition: "超参数 - 在训练前需要设置的参数，不受学习算法本身影响" },
        { term: "Cross-validation", pos: "n.", phonetic: "/krɒs ˌvælɪˈdeɪʃən/", definition: "交叉验证 - 评估模型性能的方法，通过将数据分成多个子集" },
        { term: "Grid Search", pos: "n.", phonetic: "/ɡrɪd sɜːtʃ/", definition: "网格搜索 - 寻找最佳超参数组合的系统性方法" },
        { term: "Early Stopping", pos: "n.", phonetic: "/ˈɜːli ˈstɒpɪŋ/", definition: "早停法 - 当验证误差不再下降时停止训练的正则化技术" },
        { term: "Ridge Regression", pos: "n.", phonetic: "/rɪdʒ rɪˈɡrɛʃən/", definition: "岭回归 - 使用L2正则化的线性回归" },
        { term: "Lasso Regression", pos: "n.", phonetic: "/ˈlæsəʊ rɪˈɡrɛʃən/", definition: "套索回归 - 使用L1正则化的线性回归" },
        { term: "Elastic Net", pos: "n.", phonetic: "/ɪˈlæstɪk nɛt/", definition: "弹性网络 - 结合岭回归和套索回归的方法" },
        { term: "Softmax Regression", pos: "n.", phonetic: "/ˈsɒftmæks rɪˈɡrɛʃən/", definition: "Softmax回归 - 逻辑回归的多类别扩展" },
        { term: "k-Nearest Neighbours", pos: "n.", phonetic: "/keɪ ˈnɪərɪst ˈneɪbəz/", definition: "k-近邻算法 - 基于相似度的分类和回归算法" },
        { term: "Distance metric", pos: "n.", phonetic: "/ˈdɪstəns ˈmɛtrɪk/", definition: "距离度量 - 衡量特征空间中实例之间距离的方法" },
        { term: "Minkowski distance", pos: "n.", phonetic: "/mɪŋˈkɒfski ˈdɪstəns/", definition: "闵可夫斯基距离 - 一种通用距离度量，包含欧几里得和曼哈顿距离" },
        { term: "Multiclass Classification", pos: "n.", phonetic: "/ˌmʌltiˈklɑːs ˌklæsɪfɪˈkeɪʃən/", definition: "多类分类 - 将实例分类到多个类别中" },
        { term: "Multilabel Classification", pos: "n.", phonetic: "/ˌmʌltiˈleɪbəl ˌklæsɪfɪˈkeɪʃən/", definition: "多标签分类 - 为每个实例预测多个二元标签" },
        { term: "Multioutput-Multiclass Classification", pos: "n.", phonetic: "/ˌmʌltiˈaʊtpʊt ˌmʌltiˈklɑːs ˌklæsɪfɪˈkeɪʃən/", definition: "多输出多类分类 - 多标签分类的扩展，每个标签可以有多个可能值" },
        { term: "Assumption", pos: "n.", phonetic: "/əˈsʌmpʃən/", definition: "假设 - 在没有证据的情况下接受为真的事物" },
        { term: "Excessive", pos: "adj.", phonetic: "/ɪkˈsɛsɪv/", definition: "过度的 - 超过正常或合理范围的" },
        { term: "Sensitivity", pos: "n.", phonetic: "/ˌsɛnsɪˈtɪvɪti/", definition: "敏感性 - 对微小变化的反应能力" },
        { term: "Variation", pos: "n.", phonetic: "/ˌvɛəriˈeɪʃən/", definition: "变化 - 状态、形式或质量的改变" },
        { term: "Irreducible", pos: "adj.", phonetic: "/ˌɪrɪˈdjuːsəbl/", definition: "不可约的 - 不能被简化或分解的" },
        { term: "Constraints", pos: "n.", phonetic: "/kənˈstreɪnts/", definition: "约束 - 限制或控制" },
        { term: "Via", pos: "prep.", phonetic: "/ˈvaɪə/", definition: "通过 - 经由某种方式或途径" },
        { term: "Estimation", pos: "n.", phonetic: "/ˌɛstɪˈmeɪʃən/", definition: "估计 - 对某事物的近似判断" },
        { term: "Normalized", pos: "adj.", phonetic: "/ˈnɔːməlaɪzd/", definition: "标准化的 - 使符合标准或常态" },
        { term: "Exponential", pos: "adj.", phonetic: "/ˌɛkspəˈnɛnʃəl/", definition: "指数的 - 涉及指数的数学函数" },
        { term: "Coefficient", pos: "n.", phonetic: "/ˌkəʊɪˈfɪʃənt/", definition: "系数 - 数学表达式中的乘数" },
        { term: "Partition", pos: "n.", phonetic: "/pɑːˈtɪʃən/", definition: "划分 - 将整体分成不同的部分" },
        { term: "Aggregate", pos: "v.", phonetic: "/ˈæɡrɪɡeɪt/", definition: "聚合 - 将不同元素收集或组合成一个整体" },
        { term: "Vicinity", pos: "n.", phonetic: "/vəˈsɪnɪti/", definition: "邻近 - 某地附近的区域" },
        { term: "Density", pos: "n.", phonetic: "/ˈdɛnsɪti/", definition: "密度 - 单位体积或面积内的数量" },
        { term: "Crucial", pos: "adj.", phonetic: "/ˈkruːʃəl/", definition: "关键的 - 决定性的或极其重要的" },
        { term: "Duels", pos: "n.", phonetic: "/ˈdjuːəlz/", definition: "对决 - 两人或两组之间的对抗" },
        { term: "Intensive", pos: "adj.", phonetic: "/ɪnˈtɛnsɪv/", definition: "密集的 - 需要大量集中努力或资源的" },
        { term: "Attribute", pos: "n.", phonetic: "/ˈætrɪbjuːt/", definition: "属性 - 事物的品质或特征" },
        { term: "Strictly", pos: "adv.", phonetic: "/ˈstrɪktli/", definition: "严格地 - 完全按照规则或精确地" }
    ]
}; 