// 各讲义的专业术语和四级词汇
const lectureData = {
    // 第一讲内容 - 模板：{ term: "词汇", pos: "词性", phonetic: "音标", definition: "定义" }
    1: [
        { term: "algorithm", pos: "n.", phonetic: "/ˈælɡərɪðəm/", definition: "算法 - 解决特定问题的一系列操作步骤" },
        { term: "dataset", pos: "n.", phonetic: "/ˈdeɪtəˌsɛt/", definition: "数据集 - 用于训练和测试机器学习模型的数据集合" },
        { term: "feature", pos: "n.", phonetic: "/ˈfiːtʃər/", definition: "特征 - 数据中用于预测的输入变量" },
        { term: "label", pos: "n.", phonetic: "/ˈleɪbl/", definition: "标签 - 监督学习中的目标变量或输出" },
        { term: "hypothesis", pos: "n.", phonetic: "/haɪˈpɒθəsɪs/", definition: "假设 - 模型对数据关系的假设表达式" },
        { term: "correlation", pos: "n.", phonetic: "/ˌkɔːrəˈleɪʃn/", definition: "相关性 - 变量之间的统计关系" },
        { term: "accuracy", pos: "n.", phonetic: "/ˈækjərəsi/", definition: "准确率 - 正确预测的比例" },
        { term: "precision", pos: "n.", phonetic: "/prɪˈsɪʒn/", definition: "精确率 - 正确预测为正类的比例" },
        { term: "recall", pos: "n.", phonetic: "/rɪˈkɔːl/", definition: "召回率 - 正确识别出的正类样本占所有正类样本的比例" },
        { term: "training", pos: "n.", phonetic: "/ˈtreɪnɪŋ/", definition: "训练 - 机器学习模型学习数据模式的过程" },
        { term: "machine learning", pos: "n.", phonetic: "/məˈʃiːn ˈlɜːrnɪŋ/", definition: "机器学习 - 计算机系统通过经验自动改进的科学" },
        { term: "supervised learning", pos: "n.", phonetic: "/ˈsuːpərvaɪzd ˈlɜːrnɪŋ/", definition: "监督学习 - 使用已标记数据进行训练的学习方法" },
        { term: "unsupervised learning", pos: "n.", phonetic: "/ˌʌnˈsuːpərvaɪzd ˈlɜːrnɪŋ/", definition: "无监督学习 - 在没有标记数据的情况下识别模式的学习方法" },
        { term: "classification", pos: "n.", phonetic: "/ˌklæsɪfɪˈkeɪʃn/", definition: "分类 - 将实例分配到预定义类别的任务" },
        { term: "regression", pos: "n.", phonetic: "/rɪˈɡrɛʃn/", definition: "回归 - 预测连续值的任务" },
        { term: "overfitting", pos: "n.", phonetic: "/ˌoʊvərˈfɪtɪŋ/", definition: "过拟合 - 模型过度适应训练数据，导致泛化能力差" },
        { term: "underfitting", pos: "n.", phonetic: "/ˌʌndərˈfɪtɪŋ/", definition: "欠拟合 - 模型无法捕捉数据的底层模式" },
        { term: "generalization", pos: "n.", phonetic: "/ˌdʒɛnərəlɪˈzeɪʃn/", definition: "泛化 - 模型在未见过的数据上表现良好的能力" },
        { term: "instance", pos: "n.", phonetic: "/ˈɪnstəns/", definition: "实例 - 数据集中的单个样本" },
        { term: "attribute", pos: "n.", phonetic: "/ˈætrɪbjuːt/", definition: "属性 - 描述实例的特征" },
        { term: "bias", pos: "n.", phonetic: "/ˈbaɪəs/", definition: "偏差 - 模型预测值与真实值之间的系统性差异" },
        { term: "variance", pos: "n.", phonetic: "/ˈvɛəriəns/", definition: "方差 - 模型对不同训练数据的敏感程度" },
        { term: "parameter", pos: "n.", phonetic: "/pəˈræmɪtər/", definition: "参数 - 模型内部需要从数据中学习的变量" },
        { term: "inference", pos: "n.", phonetic: "/ˈɪnfərəns/", definition: "推断 - 使用训练好的模型对新数据进行预测" },
        { term: "iteration", pos: "n.", phonetic: "/ˌɪtəˈreɪʃn/", definition: "迭代 - 重复执行特定操作的过程" },
        { term: "normalization", pos: "n.", phonetic: "/ˌnɔːrməlaɪˈzeɪʃn/", definition: "规范化 - 将数据调整到特定范围的过程" },
        { term: "outlier", pos: "n.", phonetic: "/ˈaʊtlaɪər/", definition: "异常值 - 与大多数数据明显不同的数据点" },
        { term: "preprocessing", pos: "n.", phonetic: "/ˌpriːˈprəʊsɛsɪŋ/", definition: "预处理 - 在模型训练前对数据进行清洗和转换" },
        { term: "predict", pos: "v.", phonetic: "/prɪˈdɪkt/", definition: "预测 - 使用模型对未知数据进行推断" },
        { term: "pattern", pos: "n.", phonetic: "/ˈpætərn/", definition: "模式 - 数据中的规律或结构" },
        { term: "evaluate", pos: "v.", phonetic: "/ɪˈvæljueɪt/", definition: "评估 - 测量模型性能的过程" },
        { term: "batch", pos: "n.", phonetic: "/bætʃ/", definition: "批次 - 一次处理的数据子集" },
        { term: "epoch", pos: "n.", phonetic: "/ˈiːpɒk/", definition: "轮次 - 通过整个训练数据集的一次迭代" },
        { term: "validation set", pos: "n.", phonetic: "/ˌvælɪˈdeɪʃn sɛt/", definition: "验证集 - 用于调整模型参数的数据集" },
        { term: "test set", pos: "n.", phonetic: "/tɛst sɛt/", definition: "测试集 - 用于评估最终模型性能的数据集" },
        { term: "training set", pos: "n.", phonetic: "/ˈtreɪnɪŋ sɛt/", definition: "训练集 - 用于训练模型的数据集" },
        { term: "representation", pos: "n.", phonetic: "/ˌrɛprɪzɛnˈteɪʃn/", definition: "表示 - 数据在模型中的编码方式" },
        { term: "binary", pos: "adj.", phonetic: "/ˈbaɪnəri/", definition: "二元的 - 只有两种可能值的" },
        { term: "continuous", pos: "adj.", phonetic: "/kənˈtɪnjuəs/", definition: "连续的 - 可以取任何实数值的" },
        { term: "discrete", pos: "adj.", phonetic: "/dɪˈskriːt/", definition: "离散的 - 只能取有限或可数无限个值的" },
        { term: "dimensionality", pos: "n.", phonetic: "/dɪˌmɛnʃəˈnæləti/", definition: "维度 - 描述数据的特征数量" },
        { term: "scale", pos: "v.", phonetic: "/skeɪl/", definition: "缩放 - 调整数据的量级" },
        { term: "metric", pos: "n.", phonetic: "/ˈmɛtrɪk/", definition: "度量 - 衡量性能的标准" },
        { term: "baseline", pos: "n.", phonetic: "/ˈbeɪslaɪn/", definition: "基准 - 性能比较的参考点" },
        { term: "convergence", pos: "n.", phonetic: "/kənˈvɜːrdʒəns/", definition: "收敛 - 优化过程逐渐达到最优解的状态" }
    ],
    
    // 第二讲内容
    2: [
        { term: "linear regression", pos: "n.", phonetic: "/ˈlɪniər rɪˈɡrɛʃn/", definition: "线性回归 -.使用线性方程建立自变量和因变量关系的方法" },
        { term: "gradient descent", pos: "n.", phonetic: "/ˈɡreɪdiənt dɪˈsɛnt/", definition: "梯度下降 - 通过沿着函数的梯度负方向迭代来找到局部最小值的优化算法" },
        { term: "cost function", pos: "n.", phonetic: "/kɒst ˈfʌŋkʃn/", definition: "代价函数 - 衡量模型预测值与实际值之间差异的函数" },
        { term: "least squares", pos: "n.", phonetic: "/liːst skweərz/", definition: "最小二乘法 - 找到最佳拟合线以最小化误差平方和的方法" },
        { term: "coefficient", pos: "n.", phonetic: "/ˌkoʊəˈfɪʃnt/", definition: "系数 - 线性模型中各特征的权重" },
        { term: "intercept", pos: "n.", phonetic: "/ˈɪntərˌsɛpt/", definition: "截距 - 线性模型中的常数项" },
        { term: "multicollinearity", pos: "n.", phonetic: "/ˌmʌltikoʊˌlɪniˈærəti/", definition: "多重共线性 - 自变量之间存在高相关性的情况" },
        { term: "residual", pos: "n.", phonetic: "/rɪˈzɪdjuəl/", definition: "残差 - 实际值与预测值之间的差异" },
        { term: "parameter", pos: "n.", phonetic: "/pəˈræmɪtər/", definition: "参数 - 模型中需要从数据中学习的值" },
        { term: "bias", pos: "n.", phonetic: "/ˈbaɪəs/", definition: "偏差 - 模型的预测值与实际值之间的系统性差异" },
        { term: "learning rate", pos: "n.", phonetic: "/ˈlɜːrnɪŋ reɪt/", definition: "学习率 - 在梯度下降中控制每次参数更新步长的超参数" },
        { term: "weight", pos: "n.", phonetic: "/weɪt/", definition: "权重 - 模型中表示特征重要性的系数" },
        { term: "optimization", pos: "n.", phonetic: "/ˌɒptɪmaɪˈzeɪʃn/", definition: "优化 - 寻找最优模型参数的过程" },
        { term: "convex function", pos: "n.", phonetic: "/ˈkɒnvɛks ˈfʌŋkʃn/", definition: "凸函数 - 任意两点间的线段位于函数图像上方或其上的函数" },
        { term: "derivative", pos: "n.", phonetic: "/dɪˈrɪvətɪv/", definition: "导数 - 函数在某一点的变化率" },
        { term: "partial derivative", pos: "n.", phonetic: "/ˈpɑːrʃəl dɪˈrɪvətɪv/", definition: "偏导数 - 多变量函数对单一变量的导数" },
        { term: "vector", pos: "n.", phonetic: "/ˈvɛktər/", definition: "向量 - 具有大小和方向的量" },
        { term: "matrix", pos: "n.", phonetic: "/ˈmeɪtrɪks/", definition: "矩阵 - 按行和列排列的数字矩形数组" },
        { term: "squared error", pos: "n.", phonetic: "/skweərd ˈɛrər/", definition: "平方误差 - 预测值与实际值差的平方" },
        { term: "mean squared error", pos: "n.", phonetic: "/miːn skweərd ˈɛrər/", definition: "均方误差 - 平方误差的平均值，常用的回归评估指标" },
        { term: "root mean squared error", pos: "n.", phonetic: "/ruːt miːn skweərd ˈɛrər/", definition: "均方根误差 - 均方误差的平方根" },
        { term: "batch gradient descent", pos: "n.", phonetic: "/bætʃ ˈɡreɪdiənt dɪˈsɛnt/", definition: "批量梯度下降 - 使用所有训练数据更新参数的梯度下降方法" },
        { term: "stochastic gradient descent", pos: "n.", phonetic: "/stəˈkæstɪk ˈɡreɪdiənt dɪˈsɛnt/", definition: "随机梯度下降 - 每次使用单个样本更新参数的梯度下降方法" },
        { term: "mini-batch gradient descent", pos: "n.", phonetic: "/ˈmɪni bætʃ ˈɡreɪdiənt dɪˈsɛnt/", definition: "小批量梯度下降 - 每次使用小批量样本更新参数的梯度下降方法" },
        { term: "divergence", pos: "n.", phonetic: "/daɪˈvɜːrdʒəns/", definition: "发散 - 优化过程中参数值无限增大的现象" },
        { term: "convergence", pos: "n.", phonetic: "/kənˈvɜːrdʒəns/", definition: "收敛 - 优化过程中参数值趋于稳定的状态" },
        { term: "local minimum", pos: "n.", phonetic: "/ˈloʊkl ˈmɪnɪməm/", definition: "局部最小值 - 函数在某个区域内的最小值" },
        { term: "global minimum", pos: "n.", phonetic: "/ˈɡloʊbl ˈmɪnɪməm/", definition: "全局最小值 - 函数在整个定义域内的最小值" },
        { term: "saddle point", pos: "n.", phonetic: "/ˈsædl pɔɪnt/", definition: "鞍点 - 既不是局部最小值也不是局部最大值的平稳点" },
        { term: "normal equation", pos: "n.", phonetic: "/ˈnɔːrməl ɪˈkweɪʒn/", definition: "正规方程 - 直接计算线性回归最优参数的解析方法" },
        { term: "covariance", pos: "n.", phonetic: "/koʊˈvɛəriəns/", definition: "协方差 - 衡量两个随机变量线性相关性的指标" },
        { term: "variance", pos: "n.", phonetic: "/ˈvɛəriəns/", definition: "方差 - 随机变量与其期望值差异的度量" },
        { term: "correlation coefficient", pos: "n.", phonetic: "/ˌkɔːrəˈleɪʃn koʊɪˈfɪʃnt/", definition: "相关系数 - 衡量两个变量之间线性关系强度的指标" },
        { term: "deterministic", pos: "adj.", phonetic: "/dɪˌtɜːrmɪˈnɪstɪk/", definition: "确定性的 - 在相同输入下总是产生相同输出的" },
        { term: "predictor", pos: "n.", phonetic: "/prɪˈdɪktər/", definition: "预测变量 - 用于预测目标变量的输入特征" },
        { term: "dependent variable", pos: "n.", phonetic: "/dɪˈpɛndənt ˈvɛəriəbl/", definition: "因变量 - 被预测的目标变量" },
        { term: "independent variable", pos: "n.", phonetic: "/ˌɪndɪˈpɛndənt ˈvɛəriəbl/", definition: "自变量 - 用于预测的输入变量" },
        { term: "outlier", pos: "n.", phonetic: "/ˈaʊtlaɪər/", definition: "异常值 - 与大多数数据显著不同的数据点" },
        { term: "extrapolation", pos: "n.", phonetic: "/ɪkˌstræpəˈleɪʃn/", definition: "外推 - 在训练数据范围之外进行预测" },
        { term: "interpolation", pos: "n.", phonetic: "/ɪnˌtɜːrpəˈleɪʃn/", definition: "内插 - 在训练数据范围内进行预测" },
        { term: "standardization", pos: "n.", phonetic: "/ˌstændərdaɪˈzeɪʃn/", definition: "标准化 - 将特征转换为均值为0、标准差为1的分布" },
        { term: "feature scaling", pos: "n.", phonetic: "/ˈfiːtʃər ˈskeɪlɪŋ/", definition: "特征缩放 - 将不同特征调整到相似的尺度" },
        { term: "normalization", pos: "n.", phonetic: "/ˌnɔːrməlaɪˈzeɪʃn/", definition: "归一化 - 将特征值缩放到特定区间，如[0,1]" },
        { term: "feature engineering", pos: "n.", phonetic: "/ˈfiːtʃər ˌɛndʒɪˈnɪrɪŋ/", definition: "特征工程 - 创建、选择和转换特征以提升模型性能" },
        { term: "polynomial regression", pos: "n.", phonetic: "/ˌpɒlɪˈnoʊmiəl rɪˈɡrɛʃn/", definition: "多项式回归 - 使用多项式特征的线性回归" },
        { term: "overfitting", pos: "n.", phonetic: "/ˌoʊvərˈfɪtɪŋ/", definition: "过拟合 - 模型过于复杂，在训练数据上表现好但泛化能力差" },
        { term: "underfitting", pos: "n.", phonetic: "/ˌʌndərˈfɪtɪŋ/", definition: "欠拟合 - 模型过于简单，无法捕捉数据中的模式" },
        { term: "generalization", pos: "n.", phonetic: "/ˌdʒɛnərəlɪˈzeɪʃn/", definition: "泛化 - 模型在未见过的数据上表现良好的能力" },
        { term: "scatter plot", pos: "n.", phonetic: "/ˈskætər plɒt/", definition: "散点图 - 在坐标系中显示数据点的图表" },
        { term: "regression line", pos: "n.", phonetic: "/rɪˈɡrɛʃn laɪn/", definition: "回归线 - 在散点图上最佳拟合数据点的直线" },
        { term: "regression coefficient", pos: "n.", phonetic: "/rɪˈɡrɛʃn koʊɪˈfɪʃnt/", definition: "回归系数 - 表示自变量与因变量关系的参数" },
        { term: "multivariate", pos: "adj.", phonetic: "/ˌmʌltiˈvɛəriət/", definition: "多变量的 - 涉及多个变量的" },
        { term: "univariate", pos: "adj.", phonetic: "/ˌjuːnɪˈvɛəriət/", definition: "单变量的 - 只涉及一个变量的" },
        { term: "monotonic", pos: "adj.", phonetic: "/ˌmɒnəˈtɒnɪk/", definition: "单调的 - 始终增加或始终减少的函数" },
        { term: "differentiable", pos: "adj.", phonetic: "/ˌdɪfəˈrɛnʃəbl/", definition: "可微分的 - 在每一点都有导数的函数" },
        { term: "homoscedasticity", pos: "n.", phonetic: "/ˌhoʊmoʊsɪdæˈstɪsɪti/", definition: "同方差性 - 误差项具有恒定方差的特性" },
        { term: "heteroscedasticity", pos: "n.", phonetic: "/ˌhɛtəroʊsɪdæˈstɪsɪti/", definition: "异方差性 - 误差项方差不恒定的特性" },
        { term: "cross-validation", pos: "n.", phonetic: "/krɔs ˌvælɪˈdeɪʃn/", definition: "交叉验证 - 评估模型性能的方法，通过将数据分成多个子集" }
    ],
    
    // 第三讲内容
    3: [
        { term: "logistic regression", pos: "n.", phonetic: "/ləˈdʒɪstɪk rɪˈɡrɛʃn/", definition: "逻辑回归 - 用于二分类问题的统计模型" },
        { term: "decision boundary", pos: "n.", phonetic: "/dɪˈsɪʒn ˈbaʊndri/", definition: "决策边界 - 分类算法中划分不同类别的边界" },
        { term: "sigmoid function", pos: "n.", phonetic: "/ˈsɪɡmɔɪd ˈfʌŋkʃn/", definition: "S型函数 - 将值映射到0和1之间的函数，常用于逻辑回归" },
        { term: "probability", pos: "n.", phonetic: "/ˌprɒbəˈbɪləti/", definition: "概率 - 事件发生的可能性" },
        { term: "binary classification", pos: "n.", phonetic: "/ˈbaɪnəri ˌklæsɪfɪˈkeɪʃn/", definition: "二分类 - 将实例分为两个互斥类别的任务" },
        { term: "threshold", pos: "n.", phonetic: "/ˈθrɛʃoʊld/", definition: "阈值 - 用于决定分类的截断点" },
        { term: "optimization", pos: "n.", phonetic: "/ˌɒptɪmaɪˈzeɪʃn/", definition: "优化 - 找到模型参数最佳值的过程" },
        { term: "confusion matrix", pos: "n.", phonetic: "/kənˈfjuːʒn ˈmeɪtrɪks/", definition: "混淆矩阵 - 用于评估分类模型性能的表格" },
        { term: "F1 score", pos: "n.", phonetic: "/ɛf wʌn skɔːr/", definition: "F1分数 - 精确率和召回率的调和平均值" },
        { term: "validation", pos: "n.", phonetic: "/ˌvælɪˈdeɪʃn/", definition: "验证 - 评估模型在未见过的数据上的表现的过程" },
        { term: "odds", pos: "n.", phonetic: "/ɒdz/", definition: "几率 - 事件发生的可能性与不发生的可能性之比" },
        { term: "log odds", pos: "n.", phonetic: "/lɒɡ ɒdz/", definition: "对数几率 - 几率的自然对数，也叫logit" },
        { term: "odds ratio", pos: "n.", phonetic: "/ɒdz ˈreɪʃioʊ/", definition: "优势比 - 两个事件几率的比值" },
        { term: "maximum likelihood", pos: "n.", phonetic: "/ˈmæksɪməm ˈlaɪklihʊd/", definition: "最大似然 - 寻找能使观测数据出现概率最大的参数值的方法" },
        { term: "cross-entropy", pos: "n.", phonetic: "/krɔs ˈɛntrəpi/", definition: "交叉熵 - 衡量两个概率分布差异的度量" },
        { term: "logit", pos: "n.", phonetic: "/ˈlɒdʒɪt/", definition: "Logit - 对数几率函数，逻辑回归中的线性部分" },
        { term: "true positive", pos: "n.", phonetic: "/truː ˈpɒzətɪv/", definition: "真正例 - 正确预测为正类的样本数量" },
        { term: "false positive", pos: "n.", phonetic: "/fɔːls ˈpɒzətɪv/", definition: "假正例 - 错误预测为正类的样本数量" },
        { term: "true negative", pos: "n.", phonetic: "/truː ˈnɛɡətɪv/", definition: "真负例 - 正确预测为负类的样本数量" },
        { term: "false negative", pos: "n.", phonetic: "/fɔːls ˈnɛɡətɪv/", definition: "假负例 - 错误预测为负类的样本数量" },
        { term: "ROC curve", pos: "n.", phonetic: "/ɑr oʊ si kɜrv/", definition: "ROC曲线 - 受试者工作特征曲线，展示分类器在不同阈值下的性能" },
        { term: "AUC", pos: "n.", phonetic: "/eɪ juː siː/", definition: "AUC - ROC曲线下面积，衡量分类器性能的指标" },
        { term: "precision-recall curve", pos: "n.", phonetic: "/prɪˈsɪʒn rɪˈkɔːl kɜːrv/", definition: "精确率-召回率曲线 - 展示不同阈值下精确率和召回率关系的曲线" },
        { term: "multiclass classification", pos: "n.", phonetic: "/ˌmʌltiˈklæs ˌklæsɪfɪˈkeɪʃn/", definition: "多类分类 - 将实例分配到三个或更多类别的任务" },
        { term: "one-vs-rest", pos: "n.", phonetic: "/wʌn vɜːrsəs rɛst/", definition: "一对剩余 - 多类分类的一种策略，为每个类训练一个二元分类器" },
        { term: "one-vs-one", pos: "n.", phonetic: "/wʌn vɜːrsəs wʌn/", definition: "一对一 - 多类分类的一种策略，为每对类训练一个二元分类器" },
        { term: "balanced dataset", pos: "n.", phonetic: "/ˈbælənstt ˈdeɪtəˌsɛt/", definition: "平衡数据集 - 各类别样本数量大致相等的数据集" },
        { term: "imbalanced dataset", pos: "n.", phonetic: "/ɪmˈbælənstt ˈdeɪtəˌsɛt/", definition: "不平衡数据集 - 各类别样本数量差异较大的数据集" },
        { term: "class weight", pos: "n.", phonetic: "/klæs weɪt/", definition: "类别权重 - 为不同类别分配不同重要性的系数" },
        { term: "decision function", pos: "n.", phonetic: "/dɪˈsɪʒn ˈfʌŋkʃn/", definition: "决策函数 - 分类器用于分配类别标签的函数" },
        { term: "discriminative model", pos: "n.", phonetic: "/dɪˈskrɪmɪnətɪv ˈmɒdl/", definition: "判别模型 - 直接学习条件概率分布的模型" },
        { term: "generative model", pos: "n.", phonetic: "/ˈdʒɛnərətɪv ˈmɒdl/", definition: "生成模型 - 学习联合概率分布的模型" },
        { term: "likelihood", pos: "n.", phonetic: "/ˈlaɪklihʊd/", definition: "似然 - 给定模型参数下观测数据出现的概率" },
        { term: "logistic loss", pos: "n.", phonetic: "/ləˈdʒɪstɪk lɔːs/", definition: "逻辑损失 - 逻辑回归的代价函数，也称为交叉熵损失" },
        { term: "newton's method", pos: "n.", phonetic: "/ˈnjuːtnz ˈmɛθəd/", definition: "牛顿法 - 一种求解非线性方程的迭代优化算法" },
        { term: "hypothesis testing", pos: "n.", phonetic: "/haɪˈpɒθəsɪs ˈtɛstɪŋ/", definition: "假设检验 - 基于样本数据评估关于总体的假设的统计方法" },
        { term: "confidence interval", pos: "n.", phonetic: "/ˈkɒnfɪdəns ˈɪntərvəl/", definition: "置信区间 - 包含参数真实值的估计范围" },
        { term: "principle component analysis", pos: "n.", phonetic: "/ˈprɪnsəpl kəmˈpoʊnənt əˈnæləsɪs/", definition: "主成分分析 - 一种降维技术，通过线性变换找到数据的主要变异方向" },
        { term: "regularization", pos: "n.", phonetic: "/ˌrɛɡjələraɪˈzeɪʃn/", definition: "正则化 - 防止过拟合的技术，通过对模型复杂度进行惩罚" },
        { term: "feature extraction", pos: "n.", phonetic: "/ˈfiːtʃər ɪkˈstrækʃn/", definition: "特征提取 - 从原始数据中提取有用特征的过程" },
        { term: "feature selection", pos: "n.", phonetic: "/ˈfiːtʃər sɪˈlɛkʃn/", definition: "特征选择 - 选择最相关特征子集的过程" },
        { term: "bias-variance tradeoff", pos: "n.", phonetic: "/ˈbaɪəs ˈvɛəriəns ˈtreɪdɔːf/", definition: "偏差-方差权衡 - 模型复杂度与泛化能力之间的平衡" },
        { term: "calibration", pos: "n.", phonetic: "/ˌkælɪˈbreɪʃn/", definition: "校准 - 调整模型预测概率使其接近真实概率的过程" },
        { term: "platt scaling", pos: "n.", phonetic: "/plæt ˈskeɪlɪŋ/", definition: "Platt缩放 - 一种用于校准分类器概率输出的方法" },
        { term: "isotonic regression", pos: "n.", phonetic: "/ˌaɪsəˈtɒnɪk rɪˈɡrɛʃn/", definition: "保序回归 - 一种非参数回归方法，用于概率校准" },
        { term: "decision rule", pos: "n.", phonetic: "/dɪˈsɪʒn ruːl/", definition: "决策规则 - 确定如何将预测转换为最终分类的规则" },
        { term: "cost-sensitive learning", pos: "n.", phonetic: "/kɒst ˈsɛnsɪtɪv ˈlɜːrnɪŋ/", definition: "代价敏感学习 - 考虑不同类型错误代价的学习方法" },
        { term: "posterior probability", pos: "n.", phonetic: "/pɒˈstɪəriər ˌprɒbəˈbɪləti/", definition: "后验概率 - 在给定证据下事件发生的概率" },
        { term: "prior probability", pos: "n.", phonetic: "/ˈpraɪər ˌprɒbəˈbɪləti/", definition: "先验概率 - 在获得新证据前事件发生的概率" },
        { term: "bayes' theorem", pos: "n.", phonetic: "/beɪz ˈθɪərəm/", definition: "贝叶斯定理 - 描述条件概率关系的定理" },
        { term: "categorical variable", pos: "n.", phonetic: "/ˌkætəˈɡɔːrɪkl ˈvɛəriəbl/", definition: "类别变量 - 取有限个离散值的变量" },
        { term: "dummy variable", pos: "n.", phonetic: "/ˈdʌmi ˈvɛəriəbl/", definition: "虚拟变量 - 表示类别变量的二元指示变量" },
        { term: "one-hot encoding", pos: "n.", phonetic: "/wʌn hɒt ɪnˈkoʊdɪŋ/", definition: "独热编码 - 将类别变量转换为一组二元特征的方法" },
        { term: "overfitting", pos: "n.", phonetic: "/ˌoʊvərˈfɪtɪŋ/", definition: "过拟合 - 模型过度适应训练数据，泛化能力差" },
        { term: "underfitting", pos: "n.", phonetic: "/ˌʌndərˈfɪtɪŋ/", definition: "欠拟合 - 模型不能充分学习训练数据中的模式" },
        { term: "k-fold cross-validation", pos: "n.", phonetic: "/keɪ foʊld krɔs ˌvælɪˈdeɪʃn/", definition: "K折交叉验证 - 将数据分成K个子集进行模型评估的方法" },
        { term: "stratified sampling", pos: "n.", phonetic: "/ˈstrætɪfaɪd ˈsæmplɪŋ/", definition: "分层抽样 - 保持各子集中类别分布的抽样方法" },
        { term: "grid search", pos: "n.", phonetic: "/ɡrɪd sɜːrtʃ/", definition: "网格搜索 - 通过尝试参数的所有组合来寻找最佳超参数的方法" },
        { term: "random search", pos: "n.", phonetic: "/ˈrændəm sɜːrtʃ/", definition: "随机搜索 - 通过随机采样参数空间来寻找最佳超参数的方法" },
        { term: "performance metric", pos: "n.", phonetic: "/pərˈfɔːrməns ˈmɛtrɪk/", definition: "性能指标 - 衡量模型质量的标准" },
        { term: "diagnostic", pos: "n.", phonetic: "/daɪəɡˈnɒstɪk/", definition: "诊断 - 评估模型优缺点的方法" },
        { term: "learning curve", pos: "n.", phonetic: "/ˈlɜːrnɪŋ kɜːrv/", definition: "学习曲线 - 展示模型性能随训练数据量变化的曲线" },
        { term: "validation curve", pos: "n.", phonetic: "/ˌvælɪˈdeɪʃn kɜːrv/", definition: "验证曲线 - 展示模型性能随超参数变化的曲线" },
        { term: "error analysis", pos: "n.", phonetic: "/ˈɛrər əˈnæləsɪs/", definition: "错误分析 - 研究模型错误模式的过程" }
    ],
    
    // 第四讲内容
    4: [
        { term: "regularization", pos: "n.", phonetic: "/ˌrɛɡjələraɪˈzeɪʃn/", definition: "正则化 - 防止过拟合的技术，通过对模型复杂度进行惩罚" },
        { term: "L1 regularization", pos: "n.", phonetic: "/ɛl wʌn ˌrɛɡjələraɪˈzeɪʃn/", definition: "L1正则化 - 使用绝对值函数作为惩罚项的正则化方法，也称为Lasso" },
        { term: "L2 regularization", pos: "n.", phonetic: "/ɛl tuː ˌrɛɡjələraɪˈzeɪʃn/", definition: "L2正则化 - 使用平方函数作为惩罚项的正则化方法，也称为Ridge" },
        { term: "hyperparameter", pos: "n.", phonetic: "/ˌhaɪpərpəˈræmɪtər/", definition: "超参数 - 在学习过程开始之前设置的参数" },
        { term: "feature selection", pos: "n.", phonetic: "/ˈfiːtʃər sɪˈlɛkʃn/", definition: "特征选择 - 选择最相关特征子集的过程" },
        { term: "sparsity", pos: "n.", phonetic: "/ˈspɑːrsəti/", definition: "稀疏性 - 模型中大多数系数为零的特性" },
        { term: "bias-variance trade-off", pos: "n.", phonetic: "/ˈbaɪəs ˈvɛriəns treɪd ɔːf/", definition: "偏差-方差权衡 - 模型复杂度与泛化能力之间的平衡" },
        { term: "elastic net", pos: "n.", phonetic: "/ɪˈlæstɪk nɛt/", definition: "弹性网络 - 结合L1和L2正则化的方法" },
        { term: "shrinkage", pos: "n.", phonetic: "/ˈʃrɪŋkɪdʒ/", definition: "收缩 - 减小模型系数的过程" },
        { term: "grid search", pos: "n.", phonetic: "/ɡrɪd sɜːrtʃ/", definition: "网格搜索 - 寻找最佳超参数的方法" },
        { term: "Lasso", pos: "n.", phonetic: "/ˈlæsoʊ/", definition: "Lasso回归 - 使用L1正则化的线性回归" },
        { term: "Ridge", pos: "n.", phonetic: "/rɪdʒ/", definition: "岭回归 - 使用L2正则化的线性回归" },
        { term: "penalty term", pos: "n.", phonetic: "/ˈpɛnəlti tɜːrm/", definition: "惩罚项 - 添加到代价函数中以控制模型复杂度的项" },
        { term: "regularization parameter", pos: "n.", phonetic: "/ˌrɛɡjələraɪˈzeɪʃn pəˈræmɪtər/", definition: "正则化参数 - 控制正则化强度的超参数" },
        { term: "lambda", pos: "n.", phonetic: "/ˈlæmdə/", definition: "λ - 正则化强度参数，较大的值增加惩罚" },
        { term: "norm", pos: "n.", phonetic: "/nɔːrm/", definition: "范数 - 向量大小的度量" },
        { term: "L1 norm", pos: "n.", phonetic: "/ɛl wʌn nɔːrm/", definition: "L1范数 - 向量元素绝对值之和，也称为曼哈顿距离" },
        { term: "L2 norm", pos: "n.", phonetic: "/ɛl tuː nɔːrm/", definition: "L2范数 - 向量元素平方和的平方根，也称为欧几里得范数" },
        { term: "coordinate descent", pos: "n.", phonetic: "/koʊˈɔːrdɪnət dɪˈsɛnt/", definition: "坐标下降 - 每次更新一个变量的优化算法" },
        { term: "cross-validation", pos: "n.", phonetic: "/krɔs ˌvælɪˈdeɪʃn/", definition: "交叉验证 - 评估模型性能的方法，通过将数据分成多个子集" },
        { term: "k-fold cross-validation", pos: "n.", phonetic: "/keɪ foʊld krɔs ˌvælɪˈdeɪʃn/", definition: "K折交叉验证 - 将数据分成K个子集进行模型评估的方法" },
        { term: "validation set", pos: "n.", phonetic: "/ˌvælɪˈdeɪʃn sɛt/", definition: "验证集 - 用于调整超参数的数据集" },
        { term: "test set", pos: "n.", phonetic: "/tɛst sɛt/", definition: "测试集 - 用于评估最终模型性能的数据集" },
        { term: "overfitting", pos: "n.", phonetic: "/ˌoʊvərˈfɪtɪŋ/", definition: "过拟合 - 模型过度适应训练数据，泛化能力差" },
        { term: "underfitting", pos: "n.", phonetic: "/ˌʌndərˈfɪtɪŋ/", definition: "欠拟合 - 模型过于简单，无法捕捉数据中的模式" },
        { term: "collinearity", pos: "n.", phonetic: "/koʊˌlɪniˈærəti/", definition: "共线性 - 特征之间的线性相关性" },
        { term: "coefficient path", pos: "n.", phonetic: "/koʊɪˈfɪʃnt pæθ/", definition: "系数路径 - 系数值随正则化参数变化的轨迹" },
        { term: "feature importance", pos: "n.", phonetic: "/ˈfiːtʃər ɪmˈpɔːrtns/", definition: "特征重要性 - 衡量各特征对模型预测能力的贡献" },
        { term: "high-dimensional", pos: "adj.", phonetic: "/haɪ daɪˈmɛnʃənl/", definition: "高维的 - 具有大量特征的" },
        { term: "dimensionality reduction", pos: "n.", phonetic: "/dɪˌmɛnʃəˈnæləti rɪˈdʌkʃn/", definition: "降维 - 减少特征数量的技术" },
        { term: "feature engineering", pos: "n.", phonetic: "/ˈfiːtʃər ˌɛndʒɪˈnɪərɪŋ/", definition: "特征工程 - 创建、选择和转换特征的过程" },
        { term: "LOOCV", pos: "n.", phonetic: "/ɛl oʊ oʊ siː viː/", definition: "留一交叉验证 - 每次使用一个样本作为验证集的交叉验证方法" },
        { term: "generalization error", pos: "n.", phonetic: "/ˌdʒɛnərəlɪˈzeɪʃn ˈɛrər/", definition: "泛化误差 - 模型在新数据上的预期误差" },
        { term: "training error", pos: "n.", phonetic: "/ˈtreɪnɪŋ ˈɛrər/", definition: "训练误差 - 模型在训练数据上的误差" },
        { term: "validation error", pos: "n.", phonetic: "/ˌvælɪˈdeɪʃn ˈɛrər/", definition: "验证误差 - 模型在验证数据上的误差" },
        { term: "test error", pos: "n.", phonetic: "/tɛst ˈɛrər/", definition: "测试误差 - 模型在测试数据上的误差" },
        { term: "model selection", pos: "n.", phonetic: "/ˈmɒdl sɪˈlɛkʃn/", definition: "模型选择 - 选择最佳模型架构或超参数的过程" },
        { term: "information criteria", pos: "n.", phonetic: "/ˌɪnfərˈmeɪʃn kraɪˈtɪəriə/", definition: "信息准则 - 用于模型选择的统计方法，如AIC和BIC" },
        { term: "AIC", pos: "n.", phonetic: "/eɪ aɪ siː/", definition: "赤池信息准则 - 一种平衡模型拟合和复杂度的模型选择方法" },
        { term: "BIC", pos: "n.", phonetic: "/biː aɪ siː/", definition: "贝叶斯信息准则 - 一种考虑样本量的模型选择方法" },
        { term: "degrees of freedom", pos: "n.", phonetic: "/dɪˈɡriːz əv ˈfriːdəm/", definition: "自由度 - 模型中独立参数的数量" },
        { term: "parsimony", pos: "n.", phonetic: "/ˈpɑːrsɪməni/", definition: "简约性 - 模型应尽可能简单的原则" },
        { term: "Occam's razor", pos: "n.", phonetic: "/ˈɒkəmz ˈreɪzər/", definition: "奥卡姆剃刀 - 在同等条件下，应选择最简单的解释" },
        { term: "forward selection", pos: "n.", phonetic: "/ˈfɔːrwərd sɪˈlɛkʃn/", definition: "前向选择 - 从空模型开始逐步添加特征的特征选择方法" },
        { term: "backward elimination", pos: "n.", phonetic: "/ˈbækwərd ɪˌlɪmɪˈneɪʃn/", definition: "后向消除 - 从完整模型开始逐步删除特征的特征选择方法" },
        { term: "stepwise selection", pos: "n.", phonetic: "/ˈstɛpwaɪz sɪˈlɛkʃn/", definition: "逐步选择 - 结合前向和后向的特征选择方法" },
        { term: "recursive feature elimination", pos: "n.", phonetic: "/rɪˈkɜːrsɪv ˈfiːtʃər ɪˌlɪmɪˈneɪʃn/", definition: "递归特征消除 - 基于特征重要性反复删除特征的方法" },
        { term: "filter method", pos: "n.", phonetic: "/ˈfɪltər ˈmɛθəd/", definition: "过滤法 - 基于统计指标选择特征的方法" },
        { term: "wrapper method", pos: "n.", phonetic: "/ˈræpər ˈmɛθəd/", definition: "包装法 - 使用目标模型性能来选择特征的方法" },
        { term: "embedded method", pos: "n.", phonetic: "/ɪmˈbɛdɪd ˈmɛθəd/", definition: "嵌入法 - 在模型训练过程中进行特征选择的方法" },
        { term: "mutual information", pos: "n.", phonetic: "/ˈmjuːtʃuəl ˌɪnfərˈmeɪʃn/", definition: "互信息 - 衡量两个变量相互依赖性的指标" },
        { term: "chi-square test", pos: "n.", phonetic: "/kaɪ skweər tɛst/", definition: "卡方检验 - 用于特征选择的统计检验" },
        { term: "ANOVA", pos: "n.", phonetic: "/əˈnoʊvə/", definition: "方差分析 - 用于比较多组均值的统计方法" },
        { term: "standardization", pos: "n.", phonetic: "/ˌstændərdaɪˈzeɪʃn/", definition: "标准化 - 转换特征使其均值为0、标准差为1" },
        { term: "normalization", pos: "n.", phonetic: "/ˌnɔːrməlaɪˈzeɪʃn/", definition: "归一化 - 缩放特征到特定范围，如[0,1]" },
        { term: "principal component analysis", pos: "n.", phonetic: "/ˈprɪnsəpl kəmˈpoʊnənt əˈnæləsɪs/", definition: "主成分分析 - 一种降维技术" },
        { term: "computational complexity", pos: "n.", phonetic: "/ˌkɒmpjuˈteɪʃənl kəmˈplɛksəti/", definition: "计算复杂度 - 算法执行所需的计算资源" },
        { term: "time complexity", pos: "n.", phonetic: "/taɪm kəmˈplɛksəti/", definition: "时间复杂度 - 算法执行所需的时间" },
        { term: "space complexity", pos: "n.", phonetic: "/speɪs kəmˈplɛksəti/", definition: "空间复杂度 - 算法执行所需的内存" },
        { term: "early stopping", pos: "n.", phonetic: "/ˈɜːrli ˈstɒpɪŋ/", definition: "早停 - 防止过拟合的技术，当验证误差开始增加时停止训练" },
        { term: "dropout", pos: "n.", phonetic: "/ˈdrɒpaʊt/", definition: "dropout - 防止过拟合的技术，随机忽略一部分神经元" },
        { term: "ensemble learning", pos: "n.", phonetic: "/ɒnˈsɒmbl ˈlɜːrnɪŋ/", definition: "集成学习 - 结合多个模型预测的方法" },
        { term: "bagging", pos: "n.", phonetic: "/ˈbæɡɪŋ/", definition: "bagging - 通过对训练数据随机抽样训练多个模型的集成方法" },
        { term: "boosting", pos: "n.", phonetic: "/ˈbuːstɪŋ/", definition: "boosting - 顺序训练模型，每个模型关注前一个模型的错误的集成方法" },
        { term: "stacking", pos: "n.", phonetic: "/ˈstækɪŋ/", definition: "stacking - 使用元模型组合基模型预测的集成方法" },
        { term: "random forest", pos: "n.", phonetic: "/ˈrændəm ˈfɒrɪst/", definition: "随机森林 - 一种基于决策树的集成学习方法" },
        { term: "gradient boosting", pos: "n.", phonetic: "/ˈɡreɪdiənt ˈbuːstɪŋ/", definition: "梯度提升 - 一种通过优化损失函数梯度的集成方法" },
        { term: "XGBoost", pos: "n.", phonetic: "/ɛks dʒiː buːst/", definition: "XGBoost - 一种高效的梯度提升实现" }
    ]
}; 